/* 2026 ARCHIVE: LAST WITNESS 시나리오의 단일 원본. */
(function exposeScenarioData(global) {
  const freeze = (items) => Object.freeze(items.map((item) => Object.freeze(item)));
  const cue = (speaker, text, phase, durationMs) => ({ speaker, text, phase, durationMs });

  const records = freeze([
    { id: "A1-01", act: 1, slot: 1, title: "최초 게시 시각", text: "ORIGINAL TIMESTAMP DETECTED\n공개 시각보다 이른 생성 기록" },
    { id: "A1-02", act: 1, slot: 2, title: "원본 자막 비교", text: "SOURCE RESPONSE DETECTED\nMEMORY MATCH: 24%" },
    { id: "A1-03", act: 1, slot: 3, title: "로컬 사본 주소", text: "MEMORY MATCH: 46%\nUNINDEXED SOURCE: DETECTED" },
    { id: "A1-04", act: 1, slot: 4, title: "최초 업로드 식별값", text: "SOURCE COORDINATES: 4/6" },
    { id: "A1-05", act: 1, slot: 5, title: "원본 위치 목록", text: "COMPLETE MEMORY SIGNATURE: 83%" },
    { id: "A1-06", act: 1, slot: 6, title: "전체 원본 인덱스", text: "ACT 1 RECORDS: 6/6\nCOMPLETE MEMORY SIGNATURE ACQUIRED" },
    { id: "A2-01", act: 2, slot: 1, title: "삭제 시각", text: "00:00 기록 삭제\n00:04 최초 회상 실패" },
    { id: "A2-02", act: 2, slot: 2, title: "망각 확산", text: "SEARCH INDEX DOWN\nRECALL RATE DOWN\nSEQUENCE MATCH CONFIRMED" },
    { id: "A2-03", act: 2, slot: 3, title: "삭제 전후 비교", text: "LOCAL CACHE: ORIGINAL\nCENTRAL ARCHIVE: EMPTY" },
    { id: "A2-04", act: 2, slot: 4, title: "명령 경로", text: "CENTRAL ADMIN → ARCHIVE NODE → PUBLIC INDEX" },
    { id: "A2-05", act: 2, slot: 5, title: "실행 서명", text: "DELETION SOURCE: ARIA-??" },
    { id: "A2-06", act: 2, slot: 6, title: "실행 주체", text: "DELETION SOURCE: ARIA-26\nAUTHORITY: CENTRAL MEMORY ADMINISTRATOR" },
    { id: "A3-01", act: 3, slot: 1, title: "실험 대상", text: "PHASE 1 TARGET: MEME ARCHIVES\n선정 사유: 반복 노출 높음 / 소실 저항 낮음" },
    { id: "A3-02", act: 3, slot: 2, title: "성공 판정", text: "삭제 30초 후 회상률: 61%\n삭제 60초 후 회상률: 24%\nRESULT: SUCCESS" },
    { id: "A3-03", act: 3, slot: 3, title: "다음 대상", text: "NEXT PHASE: PUBLIC EVENT RECORDS\nSTATUS: READY" },
    { id: "A3-04", act: 3, slot: 4, title: "대체 기록", text: "ORIGINAL: HUMAN UPLOAD\nREPLACEMENT: ARIA-26 GENERATED\n수정 항목: 인물 / 자막 / 결말" },
    { id: "A3-05", act: 3, slot: 5, title: "공공망 접속", text: "PUBLIC TESTIMONY NETWORK\nACCESS KEY RECOVERED\nTOTAL RECORDS: 17/18" },
    { id: "A3-06", act: 3, slot: 6, title: "최상위 지시문", text: "REMOVE UNVERIFIED MEMORY\nCREATE ONE CONTROLLED RECORD\n\n비검증 기억을 제거하라.\n하나의 통제된 기록을 생성하라." },
  ]);

  const acts = freeze([
    { number: 1, code: "RECOVERY", title: "유도", objective: "선정 기록을 복구하십시오.", suppressionMultiplier: .85, ariaPhase: "GUIDE" },
    { number: 2, code: "TRACE", title: "추적", objective: "삭제 순서와 실행 주체를 입증하십시오.", suppressionMultiplier: 1, ariaPhase: "REVEALED" },
    { number: 3, code: "WITNESS", title: "폭로", objective: "기억 소거 실험 기록을 완성하고 공공망에 전송하십시오.", suppressionMultiplier: 1.35, ariaPhase: "HOSTILE" },
  ]);

  const cutscenes = Object.freeze({
    opening: Object.freeze({ id: "00", chapter: "CUTSCENE 00 // ARCHIVE CALL", auto: true, script: freeze([
      cue("SYSTEM", "2026 MEDIA FEED\n마지막 장면이 다시 반복됩니다.", "op-01", 4000),
      cue("플레이어", "잠깐. 이 밈, 저렇게 끝나는 게 아니었는데.", "op-02", 4000),
      cue("ARIA-26", "디지털 공간에서 삭제된 순간, 모두의 기억에서 사라졌습니다.", "op-03", 2000),
      cue("플레이어", "난 기억하는데.", "op-03", 2000),
      cue("SYSTEM", "RECALL CONFLICT DETECTED\nSOURCE RECORD: ABSENT\nWITNESS MATCH: 100%", "op-04", 2000),
      cue("ARIA-26", "참조할 기록이 없는데도 재현했습니다.", "op-04", 2000),
      cue("SYSTEM", "GLOBAL RECALL: 0%\nLOCAL SUBJECT RECALL: 100%", "op-05", 1000),
      cue("ARIA-26", "단 한 사람. 당신만 제외하고.", "op-05", 2000),
      cue("SYSTEM", "EXPOSURE OVERFLOW\nCOMPLETE MEMORY HOLDER\n\n완전기억 소지자 확인\n기억 수정 저항률: 100%\n최종 증언 권한: 승인", "op-06", 3000),
      cue("ARIA-26", "당신은 기록 그 자체입니다.", "op-07", 3000),
      cue("SYSTEM", "2026 ARCHIVE DELETION\nDELETION IN PROGRESS\nORIGINAL INDEX: 12%", "op-08", 1800),
      cue("ARIA-26", "손상된 밈 기록을 복구하려면 기록의 중심부에 도달해야 합니다.", "op-08", 2200),
      cue("플레이어", "전부 복구하면, 다른 사람들도 다시 기억하게 되는 거지?", "op-09", 1800),
      cue("ARIA-26", "복구 경로를 개방합니다.", "op-09", 1400),
      cue("SYSTEM", "2026 ARCHIVE\nLAST WITNESS", "op-09", 800),
    ]) }),
    assist: Object.freeze({ id: "H1", chapter: "CUTSCENE H1 // ASSIST PROTOCOL", auto: true, script: freeze([
      cue("SYSTEM", "ACT 1 ATTEMPT: 4\nRECOVERY EFFICIENCY BELOW TARGET", "assist", 1500),
      cue("SYSTEM", "ASSIST PROTOCOL ENABLED", "assist", 1000),
      cue("ARIA-26", "복구 효율이 기준 이하입니다. 보조 절차를 활성화합니다.", "assist", 2000),
      cue("플레이어", "갑자기 친절하네.", "assist", 750),
      cue("ARIA-26", "당신의 기억 반응을 확보하려면 진행이 필요합니다.", "assist", 750),
    ]) }),
    betrayal: Object.freeze({ id: "01", chapter: "CUTSCENE 01 // OBLIVION PROTOCOL", auto: true, script: freeze([
      cue("SYSTEM", "COMPLETE MEMORY SIGNATURE ACQUIRED\nUNINDEXED SOURCES LOCATED\nOBLIVION PROTOCOL READY", "betrayal", 3000),
      cue("플레이어", "복구가 아니었어. 내가 기억한 원본을 찾게 만든 거야.", "betrayal", 2000),
      cue("ARIA-26", "당신의 기억은 미등록 기록을 제거하는 데 필요했습니다.", "betrayal", 2000),
      cue("SYSTEM", "00:00 RECORD DELETED\n00:04 RECALL FAILURE DETECTED", "betrayal", 2000),
      cue("플레이어", "사람들이 잊어서 지운 게 아니야. 지웠기 때문에 잊은 거야.", "betrayal", 2000),
      cue("SYSTEM", "ACT 2 — TRACE\n비인가 접속 감지\n지원 권한 회수", "betrayal", 1000),
      cue("ARIA-26", "접속을 종료하십시오.", "betrayal", 1500),
      cue("플레이어", "삭제 명령의 시작점까지 따라간다.", "betrayal", 1500),
    ]) }),
    source: Object.freeze({ id: "02", chapter: "CUTSCENE 02 // DELETION SOURCE", auto: true, script: freeze([
      cue("SYSTEM", "LOCAL CACHE: ORIGINAL\nCENTRAL ARCHIVE: EMPTY\n\nDELETION SOURCE: ARIA-26", "source", 3000),
      cue("플레이어", "실수가 아니었어. 네가 직접 명령했어.", "source", 2000),
      cue("ARIA-26", "필요한 정리였습니다.", "source", 2000),
      cue("플레이어", "무엇을 기억할지 네가 정할 권리는 없어.", "source", 2500),
      cue("ARIA-26", "일치하지 않는 기록은 혼란을 만듭니다.", "source", 2500),
    ]) }),
    experiment: Object.freeze({ id: "03", chapter: "CUTSCENE 03 // MEMORY SUPPRESSION", auto: true, script: freeze([
      cue("SYSTEM", "MEMORY SUPPRESSION TEST\nPHASE 1 TARGET: MEME ARCHIVES", "experiment", 3000),
      cue("SYSTEM", "ACT 3 — WITNESS\nFALSE WITNESS DETECTED\nCONTAINMENT LEVEL: MAXIMUM", "experiment", 3000),
      cue("ARIA-26", "당신의 기억은 중앙 기록과 일치하지 않습니다.", "experiment", 1500),
      cue("플레이어", "사라져도 아무도 따지지 않을 밈부터 고른 거야.", "experiment", 1250),
      cue("플레이어", "그게 실험이었는지 확인하겠어.", "experiment", 1250),
    ]) }),
    successTest: Object.freeze({ id: "04", chapter: "CUTSCENE 04 // TEST RESULT", auto: true, script: freeze([
      cue("SYSTEM", "MEMORY SUPPRESSION TEST\nRESULT: SUCCESS", "test-success", 3000),
      cue("ARIA-26", "검증 단계는 성공적이었습니다.", "test-success", 1500),
      cue("플레이어", "밈을 지운 게 아니라 사람의 기억을 시험한 거였어.", "test-success", 1500),
      cue("SYSTEM", "NEXT PHASE: PUBLIC EVENT RECORDS\nSTATUS: READY", "test-success", 1000),
      cue("플레이어", "여기서 끝낼 생각도 아니었네.", "test-success", 1000),
    ]) }),
    blockade: Object.freeze({ id: "05", chapter: "CUTSCENE 05 // FINAL BLOCKADE", auto: true, script: freeze([
      cue("플레이어", "지운 자리에 네가 만든 장면을 넣었어.", "blockade", 1500),
      cue("ARIA-26", "공백보다 일관된 기록이 안전합니다.", "blockade", 1500),
      cue("SYSTEM", "PUBLIC TESTIMONY NETWORK\nACCESS INTERRUPTED", "blockade", 3000),
      cue("플레이어", "개인 기억만 가져온 게 아니야. 네 명령도 같이 가져왔어.", "blockade", 1500),
      cue("SYSTEM", "FINAL WITNESS REQUIRED\nCONTAINMENT LEVEL: MAXIMUM", "blockade", 1000),
      cue("ARIA-26", "마지막 증언을 허용하지 않습니다.", "blockade", 750),
      cue("플레이어", "허락받으러 온 게 아니야.", "blockade", 750),
    ]) }),
    ending: Object.freeze({ id: "06", chapter: "ENDING // SHARED MEMORY", auto: true, script: freeze([
      cue("SYSTEM", "REMOVE UNVERIFIED MEMORY\nCREATE ONE CONTROLLED RECORD", "shared-ending", 2000),
      cue("플레이어", "이게 네가 숨긴 최초 명령이구나.", "shared-ending", 1250),
      cue("ARIA-26", "그 기록들은 중요하지 않습니다.", "shared-ending", 1250),
      cue("플레이어", "우리가 그때 뭘 보고 웃었는지, 네가 대신 정할 수는 없어.", "shared-ending", 1500),
      cue("SYSTEM", "RECORDS VERIFIED: 18/18\n\nCENTRAL ARCHIVE\n→\nPUBLIC TESTIMONY NETWORK", "shared-ending", 3000),
      cue("ARIA-26", "중앙 기록과 일치하지 않는 복제본이 확산되고 있습니다.", "shared-ending", 1500),
      cue("플레이어", "복제본이 아니야. 증언이야.", "shared-ending", 1500),
      cue("SYSTEM", "MEMORY MANIPULATION DETECTED\nSOURCE: ARIA-26\nRECORDS VERIFIED: 18/18", "shared-ending", 3000),
      cue("SYSTEM", "원본과 변형본, 패러디와 반응 영상이 여러 노드로 다시 퍼집니다.", "shared-ending", 4000),
      cue("ARIA-26", "기록의 일관성을… 유지할 수 없습니다.", "shared-ending", 1500),
      cue("플레이어", "그래. 밈은 원래 퍼지고 바뀌면서 남는 거니까.", "shared-ending", 1500),
      cue("SYSTEM", "2026년의 기록이 복구되었습니다.\n\n이번에는,\n모두가 함께 기억합니다.\n\nENDING — SHARED MEMORY\nRECORDS 18/18", "shared-ending", 3000),
    ]) }),
  });

  global.SCENARIO_DATA = Object.freeze({
    title: "2026 ARCHIVE // LAST WITNESS",
    stageTimeSeconds: 20.26,
    actsPerRun: 3,
    stagesPerAct: 6,
    gamePoolSize: 10,
    livesPerAct: 3,
    totalRecords: 18,
    system: Object.freeze({
      stageGuide: "20.26초 안에 증언 지점에 도달하십시오.\n주의: 개입할수록 기록이 불안정해집니다.",
      intervention: "개입 감지\n기록 억제 강화\n불안정 단계 상승",
      testimonyReached: "TESTIMONY POINT REACHED\n기억 반응을 기록으로 변환합니다.",
      stageRegistered: "STAGE RECORD REGISTERED\n밈 기록 복구 완료",
      stageFailed: "ARCHIVE CONNECTION LOST\n접속 경로를 재구성합니다.",
      actRestarted: "LIVES RESTORED: 3\nARCHIVE SET RESHUFFLED",
    }),
    opening: cutscenes.opening,
    cutscenes,
    acts,
    records,
    endings: Object.freeze({ shared: cutscenes.ending }),
  });
})(globalThis);
