/*
 * Generated by scripts/build-archive-classic.ps1.
 * This classic-script bundle mirrors js/archive/*.mjs and stages/eN_*.js and
 * stages/minigame-kit.js so index.html also works
 * when opened directly through file://, where browsers block ES module imports.
 */
(function () {
/* Source: data.mjs */
const SCENARIO = globalThis.SCENARIO_DATA;
const STAGES = globalThis.MINIGAME_CATALOG;
const GAME_TITLE = '2026 ARCHIVE';
const PROLOGUE = SCENARIO.opening.script;
const ENDING = SCENARIO.endings;
const STORAGE_KEY = 'archive-2026-minigames-v2';
const SETTINGS_KEY = 'archive-2026-settings-v1';


/* Source: audio.mjs */
class ArchiveAudio {
  constructor() {
    this.context = null;
    this.volume = 0.55;
    this.bgm = new Audio("sounds/bgm/bgm_main_theme.mp3");
    this.bgm.loop = true;
    this.bgm.preload = "auto";
    this.bgm.volume = 0;
    this.bgmStarted = false;
    this.bgmUnlockEvents = ["pointerdown", "pointerup", "click", "keydown"];
    this.unlockBgm = () => this.startBgm();
  }

  setVolume(value) {
    this.volume = Math.max(0, Math.min(1, Number(value)));
  }

  setBgmVolume(value) {
    this.bgm.volume = Math.max(0, Math.min(1, Number(value)));
  }

  startBgm() {
    this.bgmStarted = true;
    // Register before play settles so an early click or touch is never missed.
    this.bgmUnlockEvents.forEach((event) => document.addEventListener(event, this.unlockBgm));
    if (this.bgm.error) this.bgm.load();
    return this.bgm.play().then(() => {
      this.bgmUnlockEvents.forEach((event) => document.removeEventListener(event, this.unlockBgm));
      return true;
    }).catch((error) => {
      if (this.bgmStarted && error.name !== "NotAllowedError" && error.name !== "AbortError") {
        console.warn("[audio] BGM playback failed; retrying on the next input.", error);
      }
      return false;
    });
  }

  stopBgm() {
    this.bgmStarted = false;
    this.bgmUnlockEvents.forEach((event) => document.removeEventListener(event, this.unlockBgm));
    this.bgm.pause();
  }

  ensureContext() {
    if (!this.context) {
      const AudioContext = window.AudioContext || window.webkitAudioContext;
      if (AudioContext) this.context = new AudioContext();
    }
    if (this.context?.state === "suspended") this.context.resume().catch(() => {});
    return this.context;
  }

  tone(frequency, duration = 0.08, type = "sine", gain = 0.12, slide = 0) {
    if (this.volume <= 0) return;
    const context = this.ensureContext();
    if (!context) return;
    const now = context.currentTime;
    const oscillator = context.createOscillator();
    const amplifier = context.createGain();
    oscillator.type = type;
    oscillator.frequency.setValueAtTime(frequency, now);
    if (slide) oscillator.frequency.exponentialRampToValueAtTime(Math.max(30, frequency + slide), now + duration);
    amplifier.gain.setValueAtTime(Math.max(0.0001, gain * this.volume), now);
    amplifier.gain.exponentialRampToValueAtTime(0.0001, now + duration);
    oscillator.connect(amplifier).connect(context.destination);
    oscillator.start(now);
    oscillator.stop(now + duration);
  }

  play(name) {
    if (name === "click") this.tone(420, 0.05, "square", 0.05, 90);
    if (name === "action") this.tone(260, 0.06, "triangle", 0.055, 65);
    if (name === "warning") this.tone(150, 0.11, "sawtooth", 0.065, -35);
    if (name === "hit") this.tone(620, 0.09, "square", 0.055, 250);
    if (name === "success") {
      this.tone(440, 0.16, "sine", 0.07, 220);
      window.setTimeout(() => this.tone(660, 0.22, "sine", 0.07, 220), 90);
    }
    if (name === "failure") this.tone(210, 0.3, "sawtooth", 0.06, -100);
  }
}

const audio = new ArchiveAudio();




/* Source: progress.mjs */
const RECORD_STATUS = Object.freeze({
  DAMAGED: "DAMAGED", PARTIAL: "PARTIALLY RESTORED", FULL: "FULLY RESTORED", LOST: "RECORD LOST",
});
const PROGRESS_KEY = "archive-2026-recovery-v1";
const RECOVERY_RULES = Object.freeze({ partialWeight: 0.5, normalEndingRatio: 0.5 });

// Results belong to an attempt; stored records only ever improve.
function createProgressStore(stageIds, storage = null) {
  const ids = [...new Set(stageIds)];
  const records = Object.fromEntries(ids.map((id) => [id, RECORD_STATUS.DAMAGED]));
  try {
    const saved = JSON.parse(storage?.getItem(PROGRESS_KEY) || "null");
    if (saved?.version === 1) for (const id of ids) {
      if ([RECORD_STATUS.PARTIAL, RECORD_STATUS.FULL].includes(saved.records?.[id])) records[id] = saved.records[id];
    }
  } catch { /* An unavailable or damaged save must not prevent play. */ }
  const summary = () => {
    const clearedCount = ids.filter((id) => records[id] !== RECORD_STATUS.DAMAGED).length;
    const fragmentCount = ids.filter((id) => records[id] === RECORD_STATUS.FULL).length;
    const recoveryRate = ids.length ? Math.round(100 * (fragmentCount + (clearedCount - fragmentCount) * RECOVERY_RULES.partialWeight) / ids.length) : 0;
    const allCleared = ids.length > 0 && clearedCount === ids.length;
    const ending = !allCleared ? null : fragmentCount === ids.length ? "complete"
      : fragmentCount / ids.length >= RECOVERY_RULES.normalEndingRatio ? "normal" : "incomplete";
    return { totalRecords: ids.length, clearedCount, fragmentCount, recoveryRate, allCleared, ending };
  };
  return {
    status: (id) => records[id] || RECORD_STATUS.DAMAGED,
    summary,
    record(id, success, fragmentCollected) {
      if (!ids.includes(id)) throw new Error(`Unknown record: ${id}`);
      const result = !success ? RECORD_STATUS.LOST : fragmentCollected ? RECORD_STATUS.FULL : RECORD_STATUS.PARTIAL;
      if (success && records[id] !== RECORD_STATUS.FULL) {
        records[id] = result;
        try { storage?.setItem(PROGRESS_KEY, JSON.stringify({ version: 1, records })); } catch { /* Session state remains available. */ }
      }
      return { result, savedStatus: records[id], ...summary() };
    },
  };
}


/* Source: records.mjs */
function createMinigameRecords(ids, storage = null) {
  const key = 'archive-2026-minigame-bests-v1', bests = {};
  try {
    const saved = JSON.parse(storage?.getItem(key) || '{}');
    for (const id of ids) if (Number.isFinite(saved[id]?.elapsed) && saved[id].elapsed >= 0 && saved[id].elapsed <= 20.26001 && Number.isInteger(saved[id].actions) && saved[id].actions >= 0) bests[id] = saved[id];
  } catch { /* 저장소가 차단되어도 플레이 가능 */ }
  return {
    best: id => bests[id] ? { ...bests[id] } : null,
    record(id, elapsed, actions) {
      if (!ids.includes(id) || !Number.isFinite(elapsed) || elapsed < 0 || elapsed > 20.26001 || !Number.isInteger(actions) || actions < 0) throw new RangeError('Invalid clear record');
      const previous = bests[id];
      const isNew = !previous || elapsed < previous.elapsed - .00001 || Math.abs(elapsed - previous.elapsed) <= .00001 && actions < previous.actions;
      if (isNew) {
        bests[id] = { elapsed, actions };
        try { storage?.setItem(key, JSON.stringify(bests)); } catch { /* 세션 기록은 유지 */ }
      }
      return { isNew, best: { ...bests[id] } };
    },
  };
}


/* Source: plays.mjs */
/*
 * 미니게임 도감이 읽는 "한 번이라도 해 봤는가" 기록.
 *
 * progress.mjs(복구 등급)·records.mjs(최고 기록)와 성격이 다르다.
 * 그 둘은 클리어해야 남지만, 여기는 시작한 순간 남는다 —
 * 도감은 "클리어한 게임"이 아니라 "만나 본 게임"을 펼치는 화면이라서다.
 *
 * 저장소가 막혀 있어도(사생활 보호 모드 등) 플레이는 그대로 되어야 하므로
 * 실패는 전부 삼키고 세션 동안만 기억한다.
 */
const PLAY_LOG_KEY = 'archive-2026-minigame-plays-v1';

function createMinigamePlayLog(stageIds, storage = null) {
  const ids = [...new Set(stageIds)];
  const played = new Set();
  try {
    const saved = JSON.parse(storage?.getItem(PLAY_LOG_KEY) || '[]');
    if (Array.isArray(saved)) for (const id of saved) if (ids.includes(id)) played.add(id);
  } catch { /* 저장이 깨져 있어도 도감은 열려야 한다 */ }

  const persist = () => {
    try { storage?.setItem(PLAY_LOG_KEY, JSON.stringify([...played])); } catch { /* 세션 기록은 유지 */ }
  };

  return {
    has: (id) => played.has(id),
    all: () => [...played],
    count: () => played.size,
    /* 이미 있는 id면 저장소를 다시 건드리지 않는다. 스테이지 시작마다 불리는 자리라서다. */
    record(id) {
      if (!ids.includes(id) || played.has(id)) return false;
      played.add(id);
      persist();
      return true;
    },
  };
}


/* Source: run-state.mjs */
const TOTAL_TIME_MS = 20_260;

function sampleStages(ids, count = 5, random = Math.random) {
  const bag = [...new Set(ids)];
  for (let i = bag.length - 1; i > 0; i--) {
    const j = Math.floor(random() * (i + 1)); [bag[i], bag[j]] = [bag[j], bag[i]];
  }
  return bag.slice(0, count);
}

function createArchiveRunState(stageIds, totalTimeMs = TOTAL_TIME_MS) {
  let selected = sampleStages(stageIds), phase = 'menu', currentStageId = null, paused = false;
  // 한 시도의 시간 예산. QA 모드만 20.26초에서 바꿔 놓는다(js/config/qa.js).
  let budgetMs = totalTimeMs;
  let remaining = budgetMs, elapsedMs = 0;
  const cleared = new Set();
  const resolveEnding = () => cleared.size === selected.length ? 'normal' : null;
  const snapshot = () => ({
    totalTimeMs: budgetMs, totalRemainingMs: Math.round(remaining), elapsedMs, phase, paused, currentStageId,
    selectedStageIds: [...selected], clearedStageIds: [...cleared], clearedCount: cleared.size,
    totalStages: selected.length, memoryCount: cleared.size, memoryStageIds: [...cleared],
    ending: resolveEnding(),
  });
  return {
    snapshot, resolveEnding,
    reset() { selected = sampleStages(stageIds); cleared.clear(); remaining = budgetMs; elapsedMs = 0; currentStageId = null; phase = 'menu'; paused = false; return snapshot(); },
    /*
     * QA 모드 전용 — 랜덤 5개 대신 지정한 목록을 이번 판의 선택으로 쓴다.
     * (게임 브리지는 selectedStageIds에 없는 스테이지를 열어 주지 않는다.)
     */
    setSelection(ids) {
      const next = [...new Set(ids)].filter(id => stageIds.includes(id));
      if (next.length === 0) throw new RangeError('Empty stage selection');
      selected = next;
      for (const id of [...cleared]) if (!selected.includes(id)) cleared.delete(id);
      return snapshot();
    },
    /* QA 모드 전용 — 한 시도의 예산(책상 시계)을 바뀐 제한시간에 맞춘다. */
    setAttemptTime(ms) {
      const value = Number(ms);
      if (!Number.isFinite(value) || value <= 0) throw new RangeError('Invalid attempt time');
      budgetMs = Math.round(value);
      if (phase !== 'playing') remaining = budgetMs;
      return snapshot();
    },
    beginAttempt(id) {
      if (!selected.includes(id)) throw new RangeError(`Stage not selected in this run: ${id}`);
      currentStageId = id; remaining = budgetMs; paused = false; phase = 'playing'; return snapshot();
    },
    consume(ms) {
      if (phase === 'playing' && !paused) { const delta = Math.min(remaining, Math.max(0, Number(ms) || 0)); remaining -= delta; elapsedMs += delta; }
      return snapshot();
    },
    completeAttempt(success) { if (phase === 'playing' && success && currentStageId) cleared.add(currentStageId); phase = 'result'; paused = false; return snapshot(); },
    leaveAttempt() { phase = 'menu'; currentStageId = null; paused = false; return snapshot(); },
    setPaused(value) { paused = Boolean(value); return snapshot(); },
  };
}


/* Source: stages/minigame-kit.js */
/* 렌더링/충돌 도구만 공유합니다. 모든 게임 상태는 scene.state에 새로 생성합니다. */
const MINI = {
  clamp: (n, lo, hi) => Math.max(lo, Math.min(hi, n)),
  rand: (lo, hi) => lo + Math.random() * (hi - lo),
  hit: (a, b) => a.x < b.x + b.w && a.x + a.w > b.x && a.y < b.y + b.h && a.y + a.h > b.y,
  init(scene, color) {
    scene.actions = 0; scene.risk = 0; scene.accent = color;
    scene.ink = scene.add.graphics();
    scene.fieldMask = scene.make.graphics({ x: 0, y: 0, add: false });
    scene.fieldMask.fillStyle(0xffffff).fillRect(20, 144, 920, 353);
    scene.ink.setMask(scene.fieldMask.createGeometryMask());
    scene.readout = scene.add.text(32, 109, '', { fontFamily: 'Arial, sans-serif', fontSize: '19px', color: '#f4f3e9' });
    scene.instruction = scene.add.text(480, 513, scene.stage.controls, { fontFamily: 'Arial, sans-serif', fontSize: '15px', color: '#a8c6d2' }).setOrigin(0.5);
    scene.assetSprites = new Map();
    scene.spawnAt = -1;
  },
  /* 죽고 다시 시작할 때의 공통 소환 연출. 재생 시간은 MINI.SPAWN초로 0.5초를 넘지 않습니다.
     scene.elapsed(공통 게임 시간)만 사용하므로 게임 쪽에 별도 타이머가 필요 없습니다. */
  SPAWN: .42,
  summon(scene) { scene.spawnAt = scene.elapsed; },
  spawnPhase(scene) {
    const phase = (scene.elapsed - scene.spawnAt) / MINI.SPAWN;
    return scene.spawnAt >= 0 && phase >= 0 && phase < 1 ? phase : null;
  },
  /* 소환 직후 캐릭터가 부풀었다 제자리로 돌아오는 배율. 도형과 이미지에 함께 적용합니다. */
  spawnScale(scene) {
    const phase = MINI.spawnPhase(scene);
    if (phase === null) return 1;
    return phase < .45 ? .35 + phase / .45 * .8 : 1.15 - (phase - .45) / .55 * .15;
  },
  spawnFx(scene, x, y, size = 30, color = scene.accent) {
    const phase = MINI.spawnPhase(scene);
    if (phase === null) return;
    // 바깥에서 조여드는 두 겹의 링과 빨려드는 파편으로 "다시 소환됐다"를 알립니다.
    const fade = 1 - phase;
    scene.ink.lineStyle(3, color, fade).strokeCircle(x, y, size * (2.5 - 1.9 * phase));
    scene.ink.lineStyle(1, 0xfaffec, fade * .55).strokeCircle(x, y, size * (3.6 - 2.9 * phase));
    for (let i = 0; i < 7; i++) {
      const angle = i * Math.PI * 2 / 7 + phase * 1.5, radius = size * (2.2 - 1.75 * phase);
      MINI.circle(scene, x + Math.cos(angle) * radius, y + Math.sin(angle) * radius, 1 + 3 * fade, 0xfaffec, fade);
    }
    MINI.circle(scene, x, y, size * .85 * fade, 0xfaffec, fade * .7);
  },
  frame(scene, text) {
    const g = scene.ink; g.clear();
    g.fillStyle(0x0c202e).fillRoundedRect(20, 144, 920, 353, 14);
    g.lineStyle(1, scene.accent, 0.13);
    for (let x = 40; x < 940; x += 40) g.lineBetween(x, 150, x, 490);
    for (let y = 170; y < 497; y += 40) g.lineBetween(20, y, 940, y);
    scene.readout.setText(text);
  },
  box(scene, x, y, w, h, color, alpha = 1) {
    scene.ink.fillStyle(color, alpha).fillRoundedRect(x, y, w, h, Math.min(5, w / 3, h / 3));
  },
  circle(scene, x, y, r, color, alpha = 1) { scene.ink.fillStyle(color, alpha).fillCircle(x, y, r); },
  line(scene, x, y, xx, yy, color, width = 2) { scene.ink.lineStyle(width, color).lineBetween(x, y, xx, yy); },
  spike(scene, x, y, w, h, color = 0xff6584) { scene.ink.fillStyle(color).fillTriangle(x, y, x + w, y, x + w / 2, y + h); },
  goal(scene, x, y, r = 22) {
    scene.ink.lineStyle(3, 0xa7ffc6).strokeCircle(x, y, r);
    scene.ink.lineStyle(2, 0xa7ffc6, 0.3).strokeCircle(x, y, r + 7);
    MINI.circle(scene, x, y, 4, 0xa7ffc6);
  },
  /* 에셋 교체 지점: assets/minigames/manifest.js에 역할별 이미지 경로를 등록합니다.
     표시 크기만 교체하고 물리 판정은 각 게임의 기존 도형을 유지합니다. */
  actor(scene, role, key, x, y, w, h, angle = 0, color = scene.accent) {
    const texture = `${scene.stageId}:${role}`;
    if (scene.textures.exists(texture)) {
      let sprite = scene.assetSprites.get(key);
      if (!sprite) { sprite = scene.add.image(x, y, texture).setMask(scene.ink.mask); scene.assetSprites.set(key, sprite); }
      sprite.setPosition(x, y).setDisplaySize(w, h).setRotation(angle).setVisible(true);
      return;
    }
    const g = scene.ink;
    g.save(); g.translateCanvas(x, y); g.rotateCanvas(angle);
    if (role === 'person' || role === 'player' && scene.stageId === 'e8') {
      g.fillStyle(0xffddb3).fillCircle(0, -h * .33, h * .16);
      g.fillStyle(color).fillRoundedRect(-w * .36, -h * .12, w * .72, h * .34, 5);
      g.lineStyle(6, color).lineBetween(-w * .43, 0, w * .43, 0);
      g.lineBetween(-w * .15, h * .15, -w * .28, h * .43);
      g.lineBetween(w * .15, h * .15, w * .28, h * .43);
    } else if (scene.stageId === 'e2' || role === 'stone' || role === 'projectile') {
      g.fillStyle(color).fillCircle(0, 0, w / 2);
      g.lineStyle(2, 0xe9ffff, .6).strokeCircle(0, 0, w / 2 - 3);
      g.fillStyle(0x08212b).fillCircle(-w * .16, -h * .12, 2.5).fillCircle(w * .16, -h * .12, 2.5);
    } else {
      g.fillStyle(color).fillRoundedRect(-w / 2, -h / 2, w, h, Math.min(8, h / 3));
      g.fillStyle(0x08212b).fillCircle(-w * .16, -h * .12, 2.8).fillCircle(w * .16, -h * .12, 2.8);
    }
    g.restore();
  },
  hideActor(scene, key) { scene.assetSprites.get(key)?.setVisible(false); },
  meter(scene, fraction) {
    MINI.box(scene, 32, 487, 896, 4, 0x204251);
    MINI.box(scene, 32, 487, 896 * MINI.clamp(fraction, 0, 1), 4, scene.accent);
  },
};


/* Source: stages/e1_gravityDash.js */

const E1_GRAVITY_DASH = {
  // 난이도: 약 16.3초 코스. 장애물은 각각 다른 가속도로 중력에 반응합니다.
  tuning: { speed: 285, distance: 4650, jump: 465, gravity: 1250, obstacleGravity: 270 },
  build() {
    MINI.init(this, 0x67e8f9);
    this.state = { x: 0, y: 450, vy: 0, sign: 1, deaths: 0, immune: 0, obstacles: [] };
    for (let i = 0; i < 17; i++) this.state.obstacles.push({
      x: 520 + i * 245, y: i % 3 === 1 ? 250 : 441, vy: 0,
      w: i % 4 === 0 ? 46 : 32, h: 34, factor: .65 + (i % 4) * .32,
    });
    this.hurdles = Array.from({ length: 6 }, (_, i) => ({ x: 860 + i * 650, y: 443, w: 35, h: 24 }));
  },
  action() {
    const s = this.state, t = E1_GRAVITY_DASH.tuning;
    // 공중에서도 키를 누르면 장애물의 중력은 뒤집힙니다. 플레이어는 착지 후 점프.
    this.actions++; s.sign *= -1;
    if (s.y >= 449) s.vy = -t.jump;
    this.sfx('jump');
  },
  update(dt) {
    const s = this.state, t = E1_GRAVITY_DASH.tuning;
    s.x += t.speed * dt; s.immune = Math.max(0, s.immune - dt);
    s.vy += t.gravity * dt; s.y = Math.min(450, s.y + s.vy * dt);
    if (s.y === 450) s.vy = 0;
    for (const o of s.obstacles) {
      o.vy += s.sign * t.obstacleGravity * o.factor * dt;
      o.vy = MINI.clamp(o.vy, -340, 340); o.y += o.vy * dt;
      if (o.y < 173 || o.y > 441) { o.y = MINI.clamp(o.y, 173, 441); o.vy = 0; }
      if (!s.immune && MINI.hit({ x: 165, y: s.y - 15, w: 30, h: 30 }, { ...o, x: o.x - s.x + 180 })) {
        s.deaths++; s.x = Math.max(0, s.x - 340); s.y = 450; s.vy = 0; s.immune = .8;
        MINI.summon(this); this.bump(); break;
      }
    }
    if (!s.immune && this.hurdles.some(o => MINI.hit({ x: 165, y: s.y - 15, w: 30, h: 30 }, { ...o, x: o.x - s.x + 180 }))) {
      s.deaths++; s.x = Math.max(0, s.x - 340); s.y = 450; s.vy = 0; s.immune = .8; MINI.summon(this); this.bump();
    }
    this.anomaly = `장애물 중력 ${s.sign === 1 ? '↓' : '↑'} · 충돌 ${s.deaths}회`;
    this.risk = Math.min(100, this.actions * 7);
    if (s.x >= t.distance) this.finish(true);
  },
  render() {
    const s = this.state, t = E1_GRAVITY_DASH.tuning;
    MINI.frame(this, `GRAVITY ${s.sign === 1 ? '↓' : '↑'}    ${Math.floor(100 * s.x / t.distance)}%`);
    MINI.box(this, 22, 467, 916, 10, 0x2c6e85);
    for (const h of this.hurdles) {
      const x = h.x - s.x + 180;
      if (x > -50 && x < 980) MINI.spike(this, x, 467, h.w, -h.h, 0xffcf7b);
    }
    for (let i = 0; i < s.obstacles.length; i++) {
      const o = s.obstacles[i], x = o.x - s.x + 180;
      if (x > -60 && x < 1000) {
        MINI.actor(this, 'obstacle', `o${i}`, x + o.w / 2, o.y + o.h / 2, o.w, o.h, 0, 0xff6584);
        MINI.line(this, x + o.w / 2, o.y - 8, x + o.w / 2, o.y - 8 - s.sign * 18, 0xffadb8);
      } else MINI.hideActor(this, `o${i}`);
    }
    const pop = MINI.spawnScale(this);
    if (!s.immune || Math.floor(s.immune * 16) % 2) MINI.actor(this, 'player', 'player', 180, s.y, 30 * pop, 30 * pop, -s.x / 80);
    else MINI.hideActor(this, 'player');
    MINI.spawnFx(this, 180, s.y, 30);
    const goal = t.distance - s.x + 180; if (goal < 950) MINI.goal(this, goal, 433);
    MINI.meter(this, s.x / t.distance);
  },
};


/* Source: stages/e2_bounceBall.js */

const E2_BOUNCE_BALL = {
  tuning: { speed: 245, gravity: 1300, jump: 365, jumpGain: 34, maxJump: 760, goal: 2880 },
  build() {
    MINI.init(this, 0xb8f77b);
    this.state = { x: 90, y: 433, vy: 0, grounded: true, jumps: 0, deaths: 0, checkpoint: 90 };
    this.platforms = [
      { x: 0, y: 449, w: 375, h: 28 }, { x: 480, y: 429, w: 335, h: 48 },
      { x: 930, y: 449, w: 335, h: 28 }, { x: 1400, y: 415, w: 335, h: 62 },
      { x: 1860, y: 442, w: 335, h: 35 }, { x: 2320, y: 426, w: 310, h: 51 },
      { x: 2730, y: 449, w: 330, h: 28 },
    ];
  },
  action() {
    const s = this.state, t = E2_BOUNCE_BALL.tuning;
    if (!s.grounded) return;
    s.vy = -Math.min(t.maxJump, t.jump + s.jumps * t.jumpGain);
    s.grounded = false; s.jumps++; this.actions++; this.sfx('jump');
  },
  update(dt) {
    const s = this.state, t = E2_BOUNCE_BALL.tuning, previous = s.y;
    s.x = MINI.clamp(s.x + this.axis('left', 'right') * t.speed * dt, 16, 3030);
    // W/S도 공중 위치 조정에 사용. 스페이스를 길게 눌러도 점프력은 변하지 않습니다.
    s.vy += (t.gravity + this.axis('up', 'down') * 420) * dt;
    s.y += s.vy * dt; s.grounded = false;
    for (const p of this.platforms) {
      if (s.vy >= 0 && s.x + 13 > p.x && s.x - 13 < p.x + p.w && previous + 15 <= p.y + 1 && s.y + 15 >= p.y) {
        s.y = p.y - 15; s.vy = 0; s.grounded = true;
        s.checkpoint = p.x + 50;
      }
    }
    if (s.y < 202 || s.y > 535) {
      s.deaths++; s.x = s.checkpoint;
      const p = this.platforms.find(p => s.x >= p.x && s.x <= p.x + p.w);
      s.y = (p?.y ?? 449) - 15; s.vy = 0; s.grounded = true; MINI.summon(this); this.bump();
    }
    this.anomaly = `점프력 ${Math.min(t.maxJump, t.jump + s.jumps * t.jumpGain)} · 사망 ${s.deaths}회`;
    this.risk = Math.min(100, s.jumps * 9);
    if (s.x >= t.goal && s.grounded) this.finish(true);
  },
  render() {
    const s = this.state, cam = Math.max(0, s.x - 190);
    MINI.frame(this, `JUMP +${s.jumps * E2_BOUNCE_BALL.tuning.jumpGain}    CHECKPOINT ${this.platforms.findIndex(p => s.checkpoint === p.x + 50) + 1}`);
    for (let x = 22; x < 938; x += 24) MINI.spike(this, x, 153, 24, 35);
    for (const p of this.platforms) MINI.box(this, p.x - cam, p.y, p.w, p.h, 0x4f7560);
    const pop = MINI.spawnScale(this);
    MINI.actor(this, 'player', 'player', s.x - cam, s.y, 30 * pop, 30 * pop, s.x / 60);
    MINI.spawnFx(this, s.x - cam, s.y, 30);
    MINI.goal(this, E2_BOUNCE_BALL.tuning.goal - cam, 424);
    MINI.meter(this, s.x / E2_BOUNCE_BALL.tuning.goal);
  },
};


/* Source: stages/e3_humanStack.js */

const E3_HUMAN_STACK = {
  tuning: { speed: 245, speedGain: 42, maxSpeed: 920, targetHeight: 206, hold: .6, dropCooldown: .3 },
  build() {
    MINI.init(this, 0xffc27e);
    const M = Phaser.Physics.Matter.Matter;
    this.stackWorld = M.Engine.create();
    this.stackWorld.gravity.y = 1.7;
    this.stackWorld.positionIterations = 8;
    M.Composite.add(this.stackWorld.world, [
      M.Bodies.rectangle(480, 488, 916, 24, { isStatic: true, friction: .9 }),
      M.Bodies.rectangle(480, 448, 160, 56, { isStatic: true, friction: .9 }),
    ]);
    this.state = { x: 270, direction: 1, drops: 0, cooldown: 0, held: 0, height: 0 };
    this.people = [];
  },
  action() {
    const s = this.state;
    if (s.cooldown > 0) return;
    const M = Phaser.Physics.Matter.Matter;
    // 어깨가 넓고 발이 있는 사람 모양 복합 강체. 넘어져도 월드에서 제거하지 않습니다.
    const x = s.x, y = 192;
    const body = M.Body.create({ parts: [
      M.Bodies.rectangle(x, y + 4, 76, 17),
      M.Bodies.rectangle(x - 17, y + 18, 17, 18), M.Bodies.rectangle(x + 17, y + 18, 17, 18),
      M.Bodies.circle(x, y - 14, 11),
    ], friction: .85, frictionStatic: 1.2, restitution: .02 });
    M.Composite.add(this.stackWorld.world, body);
    this.people.push(body); s.drops++; this.actions++; s.cooldown = E3_HUMAN_STACK.tuning.dropCooldown;
    this.sfx('hit');
  },
  pointerDown() { E3_HUMAN_STACK.action.call(this); },
  update(dt) {
    const s = this.state, t = E3_HUMAN_STACK.tuning, M = Phaser.Physics.Matter.Matter;
    s.x += s.direction * Math.min(t.maxSpeed, t.speed + s.drops * t.speedGain) * dt;
    if (s.x < 260 || s.x > 700) { s.x = MINI.clamp(s.x, 260, 700); s.direction *= -1; }
    s.cooldown = Math.max(0, s.cooldown - dt);
    M.Engine.update(this.stackWorld, dt * 1000);
    // 떠 있는 낙하물은 높이로 세지 않습니다. 실제로 받쳐진 느린 강체만 집계합니다.
    const settled = this.people.filter(b => b.speed < .7 && Math.abs(b.angularVelocity) < .035 && b.position.y > 225);
    s.height = settled.length ? Math.max(0, 420 - Math.min(...settled.map(b => b.bounds.min.y))) : 0;
    s.held = s.height >= t.targetHeight ? s.held + dt : 0;
    this.anomaly = `낙하 속도 ${Math.round(Math.min(t.maxSpeed, t.speed + s.drops * t.speedGain))} · 잔해 ${s.drops}명`;
    this.risk = Math.min(100, s.drops * 7);
    if (s.held >= t.hold) this.finish(true, `${s.drops}명으로 ${Math.round(s.height)} 높이`);
  },
  render() {
    const s = this.state, targetY = 420 - E3_HUMAN_STACK.tuning.targetHeight;
    MINI.frame(this, `HEIGHT ${Math.round(s.height)} / ${E3_HUMAN_STACK.tuning.targetHeight}    HOLD ${s.held.toFixed(1)}s`);
    MINI.box(this, 22, 477, 916, 12, 0x475667); MINI.box(this, 400, 420, 160, 57, 0x6b7285);
    MINI.line(this, 220, targetY, 740, targetY, 0xa7ffc6);
    this.people.forEach((body, i) => MINI.actor(this, 'person', `person${i}`, body.position.x, body.position.y, 78, 50, body.angle, i % 2 ? 0x8baaff : 0xffc27e));
    MINI.line(this, s.x, 151, s.x, 190, 0x91b4c1, 1);
    MINI.actor(this, 'person', 'preview', s.x, 182, 78, 50, 0);
    MINI.meter(this, s.height / E3_HUMAN_STACK.tuning.targetHeight);
  },
  dispose() {
    if (!this.stackWorld) return;
    const M = Phaser.Physics.Matter.Matter;
    M.Composite.clear(this.stackWorld.world, false); M.Engine.clear(this.stackWorld); this.stackWorld = null;
  },
};


/* Source: stages/e4_accelerationDash.js */

const E4_ACCELERATION_DASH = {
  tuning: { turns: 10, speed: 345, gain: 27, maxSpeed: 680, tolerance: 32, minLength: 255, maxLength: 380 },
  build() {
    MINI.init(this, 0xc6a2ff);
    const t = E4_ACCELERATION_DASH.tuning;
    // 계단형 월드 좌표: 매번 길이가 달라지지만 코너 수는 정확히 tuning.turns개.
    const points = [{ x: 0, y: 0 }];
    for (let i = 0; i <= t.turns; i++) {
      const last = points[points.length - 1], length = MINI.rand(t.minLength, t.maxLength);
      points.push({ x: last.x + (i % 2 === 0 ? length : 0), y: last.y - (i % 2 ? length : 0) });
    }
    this.state = { points, segment: 0, progress: 0, misses: 0, retry: 0 };
  },
  action() {
    const s = this.state, t = E4_ACCELERATION_DASH.tuning;
    if (s.retry || s.segment >= t.turns) return;
    const a = s.points[s.segment], b = s.points[s.segment + 1], length = Math.hypot(b.x - a.x, b.y - a.y);
    this.actions++;
    if (Math.abs(length - s.progress) <= t.tolerance) {
      s.segment++; s.progress = 0; this.sfx('hit');
    } else E4_ACCELERATION_DASH.miss.call(this);
  },
  pointerDown() { E4_ACCELERATION_DASH.action.call(this); },
  press(direction) {
    const expected = this.state.segment % 2 === 0 ? 'up' : 'right';
    if (direction === expected) E4_ACCELERATION_DASH.action.call(this);
    else if (['left', 'right', 'up', 'down'].includes(direction)) { this.actions++; E4_ACCELERATION_DASH.miss.call(this); }
  },
  miss() { this.state.misses++; this.state.progress = 0; this.state.retry = .22; MINI.summon(this); this.bump(); },
  update(dt) {
    const s = this.state, t = E4_ACCELERATION_DASH.tuning;
    s.retry = Math.max(0, s.retry - dt);
    if (!s.retry) s.progress += Math.min(t.maxSpeed, t.speed + s.segment * t.gain) * dt;
    const a = s.points[s.segment], b = s.points[s.segment + 1], length = Math.hypot(b.x - a.x, b.y - a.y);
    if (s.segment === t.turns && s.progress >= length) this.finish(true);
    else if (s.progress > length + t.tolerance) E4_ACCELERATION_DASH.miss.call(this);
    this.anomaly = `속도 ${Math.round(Math.min(t.maxSpeed, t.speed + s.segment * t.gain))} · 코너 ${s.segment}/${t.turns}`;
    this.risk = s.segment * 9;
  },
  render() {
    const s = this.state, t = E4_ACCELERATION_DASH.tuning;
    MINI.frame(this, `TURN ${s.segment} / ${t.turns}    MISS ${s.misses}    ${s.segment < t.turns ? `다음 ${s.segment % 2 === 0 ? 'W ↑' : 'D →'} · 초록 구역에서 꺾기` : '마지막 직선!'}`);
    const a = s.points[s.segment], b = s.points[s.segment + 1], length = Math.hypot(b.x - a.x, b.y - a.y);
    const px = a.x + (b.x - a.x) * s.progress / length, py = a.y + (b.y - a.y) * s.progress / length;
    // 진행 방향을 오른쪽으로 회전해 다음 코너를 충분히 미리 보여줍니다.
    const vertical = s.segment % 2 === 1;
    const project = p => vertical ? { x: 330 - (p.y - py), y: 365 + (p.x - px) } : { x: 330 + p.x - px, y: 365 + p.y - py };
    for (let i = Math.max(0, s.segment - 1); i < Math.min(s.points.length - 1, s.segment + 3); i++) {
      const p = project(s.points[i]), q = project(s.points[i + 1]);
      MINI.line(this, p.x, p.y, q.x, q.y, 0x443564, 60);
      MINI.line(this, p.x, p.y, q.x, q.y, 0x957ab7, 2);
      if (i < t.turns) MINI.goal(this, q.x, q.y, t.tolerance);
      else MINI.goal(this, q.x, q.y, 25);
    }
    const pop = MINI.spawnScale(this);
    MINI.actor(this, 'player', 'player', 330, 365, 28 * pop, 28 * pop, Math.PI / 4);
    MINI.spawnFx(this, 330, 365, 28);
    MINI.meter(this, s.segment / t.turns);
  },
};


/* Source: stages/e5_slingshot.js */

const E5_SLINGSHOT = {
  tuning: { force: 8.4, decay: .045, minPower: .76, gravity: 640, maxPull: 112, cooldown: .38, targetHP: 29 },
  build() {
    MINI.init(this, 0xffbd69);
    this.state = { shots: 0, cooldown: 0, drag: null, balls: [], targets: [] };
    for (let i = 0; i < 6; i++) this.state.targets.push({ x: 650 + (i % 3) * 86, y: 424 - Math.floor(i / 3) * 53, w: 38, h: 46, hp: E5_SLINGSHOT.tuning.targetHP });
  },
  power() { return Math.max(E5_SLINGSHOT.tuning.minPower, 1 - this.state.shots * E5_SLINGSHOT.tuning.decay); },
  pointerDown(x, y) {
    if (this.state.cooldown || Math.hypot(x - 164, y - 382) > 55) return;
    this.state.drag = { x: 164, y: 382 };
    E5_SLINGSHOT.pointerMove.call(this, x, y);
  },
  pointerMove(x, y) {
    if (!this.state.drag) return;
    const dx = x - 164, dy = y - 382, length = Math.max(1, Math.hypot(dx, dy)), scale = Math.min(1, E5_SLINGSHOT.tuning.maxPull / length);
    this.state.drag = { x: 164 + dx * scale, y: 382 + dy * scale };
  },
  pointerUp() {
    const s = this.state, d = s.drag, t = E5_SLINGSHOT.tuning;
    if (!d) return;
    s.drag = null;
    if (Math.hypot(d.x - 164, d.y - 382) < 8) return;
    const power = E5_SLINGSHOT.power.call(this);
    s.balls.push({ x: d.x, y: d.y, vx: (164 - d.x) * t.force * power, vy: (382 - d.y) * t.force * power, power, age: 0, hit: new Set(), id: s.shots });
    s.shots++; this.actions++; s.cooldown = t.cooldown; this.sfx('jump');
  },
  cancelInput() { this.state.drag = null; },
  update(dt) {
    const s = this.state, t = E5_SLINGSHOT.tuning;
    s.cooldown = Math.max(0, s.cooldown - dt);
    for (const b of s.balls) {
      b.age += dt; b.vy += t.gravity * dt; b.x += b.vx * dt; b.y += b.vy * dt;
      if (b.y > 457) { b.y = 457; b.vy *= -.36; b.vx *= .78; }
      s.targets.forEach((target, i) => {
        if (target.hp <= 0 || b.hit.has(i) || !MINI.hit({ x: b.x - 12, y: b.y - 12, w: 24, h: 24 }, target)) return;
        target.hp = Math.max(0, target.hp - Math.max(6, Math.hypot(b.vx, b.vy) * .1 * b.power));
        b.hit.add(i); b.vx *= .73; b.vy -= 60; this.sfx('hit');
      });
    }
    s.balls = s.balls.filter(b => {
      const keep = b.age < 3.2 && b.x < 980 && b.x > -30;
      if (!keep) { this.assetSprites.get(`ball${b.id}`)?.destroy(); this.assetSprites.delete(`ball${b.id}`); }
      return keep;
    });
    const left = s.targets.filter(o => o.hp > 0).length;
    this.anomaly = `고무줄 힘 ${Math.round(E5_SLINGSHOT.power.call(this) * 100)}% · 남은 목표 ${left}`;
    this.risk = (1 - E5_SLINGSHOT.power.call(this)) * 180;
    if (!left) this.finish(true);
  },
  render() {
    const s = this.state, d = s.drag ?? { x: 164, y: 382 }, power = E5_SLINGSHOT.power.call(this), t = E5_SLINGSHOT.tuning;
    MINI.frame(this, `TARGET ${s.targets.filter(o => o.hp <= 0).length} / 6    POWER ${Math.round(power * 100)}%`);
    MINI.box(this, 25, 471, 910, 9, 0x695e4b);
    MINI.line(this, 146, 447, 137, 358, 0xa78260, 12); MINI.line(this, 146, 404, 184, 357, 0xa78260, 12);
    MINI.line(this, 137, 360, d.x, d.y, 0xffd99b, 3); MINI.line(this, 184, 357, d.x, d.y, 0xffd99b, 3);
    MINI.actor(this, 'projectile', 'ready', d.x, d.y, 26, 26);
    if (s.drag) for (let i = 1; i <= 16; i++) {
      const time = i * .065;
      MINI.circle(this, d.x + (164 - d.x) * t.force * power * time, d.y + (382 - d.y) * t.force * power * time + .5 * t.gravity * time * time, 2, 0xffe1b8, .6);
    }
    s.targets.forEach((o, i) => {
      if (o.hp <= 0) { MINI.hideActor(this, `target${i}`); return; }
      MINI.actor(this, 'target', `target${i}`, o.x + o.w / 2, o.y + o.h / 2, o.w, o.h, 0, 0xfa7a91);
      MINI.box(this, o.x, o.y - 8, o.w * o.hp / t.targetHP, 4, 0xa7ffc6);
    });
    for (const b of s.balls) MINI.actor(this, 'projectile', `ball${b.id}`, b.x, b.y, 24, 24, b.age * 8);
  },
};


/* Source: stages/e6_gravityFlight.js */

const E6_GRAVITY_FLIGHT = {
  tuning: { speed: 255, distance: 4200, gravity: 640, gravityLoss: 35, minGravity: 240, lift: 570, liftGain: 24, maxLift: 850, gap: 155, knockback: 245 },
  build() {
    MINI.init(this, 0x7cd9ff);
    this.state = { x: 0, y: 323, vy: 0, presses: 0, hits: 0, immune: 0 };
    this.gates = Array.from({ length: 12 }, (_, i) => ({ x: 500 + i * 305, y: 314 + Math.sin(i * 1.7) * 65 }));
  },
  action() { this.state.presses++; this.actions++; this.sfx('jump'); },
  update(dt) {
    const s = this.state, t = E6_GRAVITY_FLIGHT.tuning;
    const gravity = Math.max(t.minGravity, t.gravity - s.presses * t.gravityLoss);
    const lift = Math.min(t.maxLift, t.lift + s.presses * t.liftGain);
    s.x += t.speed * dt; s.immune = Math.max(0, s.immune - dt);
    s.vy = MINI.clamp(s.vy + (this.held('action') ? -lift : gravity) * dt, -340, 320);
    s.y += s.vy * dt;
    const gate = this.gates.find(g => Math.abs(g.x - s.x) < 45 && (s.y - 13 < g.y - t.gap / 2 || s.y + 13 > g.y + t.gap / 2));
    if (!s.immune && (gate || s.y < 169 || s.y > 467)) {
      s.hits++; s.x = Math.max(0, s.x - t.knockback); s.y = gate?.y ?? MINI.clamp(s.y, 220, 415); s.vy = 0; s.immune = .85; MINI.summon(this); this.bump();
    }
    s.y = MINI.clamp(s.y, 168, 468);
    this.anomaly = `중력 ${gravity} · 상승 ${lift} · 충돌 ${s.hits}회`;
    this.risk = Math.min(100, s.presses * 6);
    if (s.x >= t.distance) this.finish(true);
  },
  render() {
    const s = this.state, t = E6_GRAVITY_FLIGHT.tuning;
    MINI.frame(this, `FLIGHT ${Math.floor(s.x / t.distance * 100)}%    ${this.held('action') ? '↑ 상승' : '↓ 하강'}    PUSH BACK ${s.hits}`);
    for (const gate of this.gates) {
      const x = gate.x - s.x + 180;
      if (x < -50 || x > 990) continue;
      MINI.box(this, x - 30, 153, 60, gate.y - t.gap / 2 - 153, 0x4c657f);
      MINI.box(this, x - 30, gate.y + t.gap / 2, 60, 480 - gate.y - t.gap / 2, 0x4c657f);
      MINI.line(this, x - 30, gate.y - t.gap / 2, x + 30, gate.y - t.gap / 2, 0xff779b, 5);
      MINI.line(this, x - 30, gate.y + t.gap / 2, x + 30, gate.y + t.gap / 2, 0xff779b, 5);
    }
    const pop = MINI.spawnScale(this);
    MINI.actor(this, 'player', 'player', 180, s.y, 36 * pop, 28 * pop, s.vy / 900);
    MINI.spawnFx(this, 180, s.y, 32);
    if (this.held('action')) MINI.spike(this, 146, s.y - 8, -MINI.rand(12, 28), 18, 0xffc47e);
    MINI.goal(this, t.distance - s.x + 180, 316);
    MINI.meter(this, s.x / t.distance);
  },
};


/* Source: stages/e7_roulette.js */

const E7_ROULETTE = {
  tuning: { minSpeed: 5, maxSpeed: 18, minSpinSeconds: 1.1 },
  build() {
    MINI.init(this, 0xfca8d6);
    this.add.text(723, 243, '당첨', { fontFamily: 'Arial', fontSize: '18px', color: '#ffcf7b' });
    this.add.text(723, 276, '꽝', { fontFamily: 'Arial', fontSize: '18px', color: '#a6b7ce' });
    this.state = { rotation: MINI.rand(0, Math.PI * 2), misses: 0, spinning: false, speed: 0, drag: null, cooldown: 0 };
  },
  pointerDown(x, y) {
    const s = this.state, radius = Math.hypot(x - 480, y - 321);
    if (s.spinning || s.cooldown || radius < 25 || radius > 155) return;
    s.drag = { last: Math.atan2(y - 321, x - 480), travel: 0, age: 0, velocity: 0, idle: 0 };
  },
  pointerMove(x, y) {
    const s = this.state, d = s.drag;
    if (!d) return;
    const angle = Math.atan2(y - 321, x - 480);
    const delta = Math.atan2(Math.sin(angle - d.last), Math.cos(angle - d.last));
    d.travel += Math.abs(delta); d.velocity = delta / Math.max(.016, d.idle); d.idle = 0; d.last = angle; s.rotation += delta;
  },
  pointerUp() {
    const s = this.state, d = s.drag, t = E7_ROULETTE.tuning;
    s.drag = null;
    if (!d || d.travel < .1) return;
    const direction = Math.sign(d.velocity) || 1;
    s.speed = direction * MINI.clamp(Math.abs(d.velocity), t.minSpeed, t.maxSpeed);
    // 균일한 한 바퀴의 추가 회전량으로 최종 각도를 균일하게 만듭니다.
    // 속도/당기는 위치에 관계없이 면적 1/N이 실제 당첨 확률 1/N이 됩니다.
    // 이 회전량에 맞는 마찰로 자연스럽게 멈추며, 당첨 판정 자체는 정지한 칸을 따릅니다.
    const travel = Math.abs(s.speed) * t.minSpinSeconds / 2 + MINI.rand(0, Math.PI * 2);
    s.deceleration = s.speed * s.speed / (2 * travel);
    s.spinning = true; this.actions++; this.sfx('click');
  },
  cancelInput() { this.state.drag = null; },
  update(dt) {
    const s = this.state;
    s.cooldown = Math.max(0, s.cooldown - dt);
    if (s.drag) { s.drag.age += dt; s.drag.idle += dt; }
    if (s.spinning) {
      const movingDt = Math.min(dt, Math.abs(s.speed) / s.deceleration);
      const next = Math.sign(s.speed) * Math.max(0, Math.abs(s.speed) - s.deceleration * dt);
      s.rotation += (s.speed + next) * .5 * movingDt; s.speed = next;
      if (Math.abs(next) < .001) {
        s.spinning = false;
        const tau = Math.PI * 2, atPointer = ((-Math.PI / 2 - s.rotation) % tau + tau) % tau;
        if (atPointer < tau / (2 * (s.misses + 1))) this.finish(true, `${this.actions}번째 추첨 당첨`);
        else { s.misses++; s.cooldown = .35; this.sfx('failure'); }
      }
    }
    this.anomaly = `당첨 영역 1/${2 * (s.misses + 1)} · ${s.spinning ? '추첨 중' : s.cooldown ? '꽝! 다시 돌리세요' : '룰렛을 휙 돌리세요'}`;
    this.risk = Math.min(100, s.misses * 17);
  },
  render() {
    const s = this.state, tau = Math.PI * 2, angle = tau / (2 * (s.misses + 1));
    MINI.frame(this, `PRIZE DRAW    당첨 영역 1 / ${2 * (s.misses + 1)}    ${s.spinning ? '돌아가는 중…' : '마우스로 원을 따라 휙! '}`);
    MINI.circle(this, 480, 321, 158, 0x725779); MINI.circle(this, 480, 321, 150, 0x2b344c);
    const points = [{ x: 480, y: 321 }];
    for (let i = 0; i <= 60; i++) points.push({ x: 480 + Math.cos(s.rotation + angle * i / 60) * 150, y: 321 + Math.sin(s.rotation + angle * i / 60) * 150 });
    this.ink.fillStyle(0xffcf7b).fillPoints(points, true);
    for (let i = 0; i < 40; i++) {
      const a = s.rotation + i * tau / 40;
      MINI.circle(this, 480 + Math.cos(a) * 153, 321 + Math.sin(a) * 153, 2, 0xfff1dd);
    }
    MINI.circle(this, 480, 321, 28, 0x142c3b);
    MINI.actor(this, 'prize', 'prize', 480, 321, 30, 30, 0, 0xfca8d6);
    MINI.spike(this, 465, 151, 30, 28, 0xfaffec);
    MINI.line(this, 675, 254, 707, 254, 0xffcf7b, 14);
    MINI.line(this, 675, 287, 707, 287, 0x66748f, 14);
  },
};


/* Source: stages/e8_seesaw.js */

const E8_SEESAW = {
  tuning: { drops: 7, moveSpeed: 245, playerMass: 12, inertia: 1900, damping: 3.7, beamHalf: 350, pivotY: 350, floorY: 477 },
  build() {
    MINI.init(this, 0x91ead7);
    this.state = { x: -100, angle: .015, omega: 0, count: 0, weights: [], age: 0 };
    this.dropPlan = Array.from({ length: E8_SEESAW.tuning.drops }, (_, i) => ({
      time: 1.1 + i * 2.45, x: MINI.rand(105, 280), mass: MINI.rand(.8, 1.4),
    }));
  },
  press(direction) { if (direction === 'left' || direction === 'right') this.actions++; },
  update(dt) {
    const s = this.state, t = E8_SEESAW.tuning;
    s.age += dt;
    s.x = MINI.clamp(s.x + this.axis('left', 'right') * t.moveSpeed * dt, -330, -42);
    if (s.count < this.dropPlan.length && s.age >= this.dropPlan[s.count].time) {
      const plan = this.dropPlan[s.count++]; s.weights.push({ ...plan, y: 154, vy: 0, landed: false });
    }
    for (const w of s.weights) if (!w.landed) {
      w.vy += 700 * dt; w.y += w.vy * dt;
      if (w.y >= t.pivotY + Math.sin(s.angle) * w.x - 16) { w.landed = true; s.omega += w.mass * .055; this.sfx('hit'); }
    }
    const rightTorque = 1200 + s.weights.filter(w => w.landed).reduce((sum, w) => sum + w.mass * w.x, 0);
    s.omega += ((rightTorque + s.x * t.playerMass) * Math.cos(s.angle) / t.inertia - s.omega * t.damping) * dt;
    s.angle += s.omega * dt;
    // 우리 쪽 끝은 바닥에 닿아도 받쳐집니다. 실패 조건은 반대쪽 끝만입니다.
    const contact = Math.asin((t.floorY - t.pivotY - 7) / t.beamHalf);
    if (s.angle < -contact) { s.angle = -contact; s.omega = Math.max(0, s.omega); }
    if (s.angle >= contact) this.finish(false, '반대편이 바닥에 닿았습니다.');
    this.anomaly = `랜덤 추 ${s.count}/${t.drops} · 반대편 여유 ${Math.max(0, Math.round(t.floorY - t.pivotY - Math.sin(s.angle) * t.beamHalf - 7))}`;
    this.risk = MINI.clamp(s.angle / contact * 100, 0, 100);
  },
  timeout() { return true; },
  render() {
    const s = this.state, t = E8_SEESAW.tuning, c = Math.cos(s.angle), sn = Math.sin(s.angle);
    MINI.frame(this, `BALANCE    ${s.count} / ${t.drops}    A ← 바깥쪽 · D → 중심`);
    MINI.box(this, 22, t.floorY, 916, 10, 0x4a6668);
    MINI.spike(this, 448, 471, 64, -121, 0x446e78);
    MINI.line(this, 480 - c * 350, t.pivotY - sn * 350, 480 + c * 350, t.pivotY + sn * 350, 0xa9bcce, 13);
    MINI.line(this, 480, t.pivotY, 480 + c * 350, t.pivotY + sn * 350, s.angle > .2 ? 0xff6584 : 0xffc47e, 13);
    MINI.circle(this, 480, t.pivotY, 12, 0xefffe7);
    MINI.actor(this, 'player', 'player', 480 + s.x * c, t.pivotY + s.x * sn - 26, 39, 48, s.angle);
    MINI.actor(this, 'weight', 'base', 480 + 100 * c, t.pivotY + 100 * sn - 20, 43, 33, s.angle, 0xffc47e);
    s.weights.forEach((w, i) => MINI.actor(this, 'weight', `w${i}`, 480 + w.x * c, w.landed ? t.pivotY + w.x * sn - 16 : w.y, 24 + w.mass * 8, 30, w.landed ? s.angle : 0, 0xffa8b8));
    const next = this.dropPlan[s.count];
    if (next && next.time - s.age < .85) { MINI.line(this, 480 + next.x, 160, 480 + next.x, 215, 0xff6584); MINI.spike(this, 470 + next.x, 205, 20, 14); }
    MINI.meter(this, this.elapsed / this.timeLimit);
  },
};


/* Source: stages/e9_iceCurling.js */

const E9_ICE_CURLING = {
  tuning: { friction: 220, decay: .69, minFriction: 26, force: 5.7, maxPull: 130, targetRadius: 41, stoneRadius: 14 },
  build() {
    MINI.init(this, 0xabe5ff);
    this.state = { x: 166, y: 361, vx: 0, vy: 0, failures: 0, moving: false, drag: null, cooldown: 0, hold: 0 };
    this.target = { x: 769, y: 287 };
  },
  friction() { const t = E9_ICE_CURLING.tuning; return Math.max(t.minFriction, t.friction * t.decay ** this.state.failures); },
  pointerDown(x, y) {
    const s = this.state;
    if (s.moving || s.cooldown || Math.hypot(x - s.x, y - s.y) > 43) return;
    s.drag = { x: s.x, y: s.y };
  },
  pointerMove(x, y) {
    const s = this.state, t = E9_ICE_CURLING.tuning;
    if (!s.drag) return;
    const dx = x - s.x, dy = y - s.y, scale = Math.min(1, t.maxPull / Math.max(1, Math.hypot(dx, dy)));
    s.drag = { x: s.x + dx * scale, y: s.y + dy * scale };
  },
  pointerUp() {
    const s = this.state, d = s.drag;
    s.drag = null;
    if (!d || Math.hypot(d.x - s.x, d.y - s.y) < 5) return;
    s.vx = (s.x - d.x) * E9_ICE_CURLING.tuning.force; s.vy = (s.y - d.y) * E9_ICE_CURLING.tuning.force;
    s.moving = true; s.hold = 0; this.actions++; this.sfx('jump');
  },
  cancelInput() { this.state.drag = null; },
  retryStone() {
    const s = this.state;
    s.failures++; s.moving = false; s.cooldown = .28; s.x = 166; s.y = 361; s.vx = s.vy = s.hold = 0;
    MINI.summon(this); this.sfx('failure');
  },
  update(dt) {
    const s = this.state, t = E9_ICE_CURLING.tuning;
    s.cooldown = Math.max(0, s.cooldown - dt);
    if (s.moving) {
      const speed = Math.hypot(s.vx, s.vy), next = Math.max(0, speed - E9_ICE_CURLING.friction.call(this) * dt);
      if (speed) {
        s.x += s.vx / speed * (speed + next) * .5 * dt; s.y += s.vy / speed * (speed + next) * .5 * dt;
        s.vx *= next / speed; s.vy *= next / speed;
      }
      if (s.x < 37 || s.x > 923 || s.y < 167 || s.y > 470) E9_ICE_CURLING.retryStone.call(this);
      else if (next === 0) {
        if (Math.hypot(s.x - this.target.x, s.y - this.target.y) <= t.targetRadius - t.stoneRadius) {
          s.hold += dt; if (s.hold >= .2) this.finish(true);
        } else E9_ICE_CURLING.retryStone.call(this);
      }
    }
    this.anomaly = `마찰 ${Math.round(E9_ICE_CURLING.friction.call(this))} · 실패 ${s.failures}회 · ${s.moving ? '미끄러지는 중' : '새 돌 준비'}`;
    this.risk = Math.min(100, s.failures * 18);
  },
  render() {
    const s = this.state, target = this.target;
    MINI.frame(this, `ICE ${Math.round(E9_ICE_CURLING.friction.call(this))}    SHOT ${this.actions}    과녁 안에 돌 전체를 멈추세요`);
    MINI.box(this, 32, 158, 896, 321, 0xc7e8f0, .12);
    for (let y = 187; y < 466; y += 35) MINI.line(this, 55, y, 905, y - 18, 0xd6f5ff, .5);
    MINI.circle(this, target.x, target.y, 71, 0x719dd5, .5);
    MINI.circle(this, target.x, target.y, 53, 0xe6faff, .7);
    MINI.circle(this, target.x, target.y, 41, 0xf77891, .85);
    MINI.circle(this, target.x, target.y, 14, 0xf5feff);
    if (s.drag) {
      MINI.line(this, s.drag.x, s.drag.y, s.x, s.y, 0xffdc90, 3);
      MINI.line(this, s.x, s.y, s.x + (s.x - s.drag.x) * 1.4, s.y + (s.y - s.drag.y) * 1.4, 0xffdc90, 2);
      MINI.circle(this, s.drag.x, s.drag.y, 6, 0xffdc90);
    }
    const pop = MINI.spawnScale(this);
    MINI.actor(this, 'stone', 'stone', s.x, s.y, 28 * pop, 28 * pop, 0, 0xffd78f);
    MINI.line(this, s.x - 7, s.y - 3, s.x + 7, s.y - 3, 0x735743, 5);
    MINI.spawnFx(this, s.x, s.y, 28);
  },
};


/* Source: stages/e10_numberDecode.js */

const PLAYER = Object.freeze({ width: 30, height: 44 });
const GROUND_Y = 474;

const moveTowardZero = (value, amount) => (
  Math.abs(value) <= amount ? 0 : value - Math.sign(value) * amount
);

function makeTarget() {
  const first = 1 + Math.floor(Math.random() * 9);
  return `${first}${Math.floor(Math.random() * 10)}${Math.floor(Math.random() * 10)}${Math.floor(Math.random() * 10)}`;
}

const E10_NUMBER_DECODE = {
  tuning: {
    acceleration: 1250,
    maxSpeed: 300,
    gravity: 1650,
    jump: 700,
    baseFriction: 820,
    frictionLoss: 150,
    minFriction: 70,
    minTraction: .32,
  },

  traction(state) {
    const t = E10_NUMBER_DECODE.tuning;
    return Math.max(t.minTraction, state.friction / t.baseFriction);
  },

  build() {
    MINI.init(this, 0xf4c76b);
    const target = makeTarget();
    this.state = {
      x: 480,
      y: GROUND_Y - PLAYER.height / 2,
      vx: 0,
      vy: 0,
      grounded: true,
      target,
      input: '',
      directionPresses: 0,
      friction: E10_NUMBER_DECODE.tuning.baseFriction,
      mistakes: 0,
      feedback: '숫자 블록의 아랫면을 점프로 터치하세요.',
      feedbackUntil: 2.2,
      lastHit: null,
      lastHitCorrect: true,
    };

    this.digitBlocks = Array.from({ length: 10 }, (_, digit) => ({
      digit: String(digit),
      x: 38 + digit * 89,
      y: 250,
      w: 68,
      h: 50,
    }));
    const targetStyle = {
      fontFamily: 'monospace', fontSize: '42px', fontStyle: 'bold',
      color: '#fff4bf', stroke: '#7a315a', strokeThickness: 3,
    };
    this.targetGlyphs = [...target].map((digit, index) => this.add.text(420 + index * 40, 193, digit, targetStyle).setOrigin(.5));
    this.targetScribbles = [...target].flatMap((digit, index) => {
      const x = 420 + index * 40;
      const offset = (Number(digit) * 5 + index * 3) % 9 - 4;
      return [
        { x1: x - 15, y1: 177 + offset, x2: x + 15, y2: 207 - offset, color: 0xff4f87, width: 3 },
        { x1: x - 14, y1: 207, x2: x + 14, y2: 179 + offset, color: 0x67e8ff, width: 2 },
        { x1: x - 17, y1: 188 - offset, x2: x + 17, y2: 196 + offset, color: 0xff4f87, width: 2 },
      ];
    });
    this.scribbleInk = this.add.graphics();
    this.blockLabels = this.digitBlocks.map(block => this.add.text(block.x + block.w / 2, block.y + block.h / 2, block.digit, {
      fontFamily: 'monospace', fontSize: '27px', fontStyle: 'bold', color: '#102536',
    }).setOrigin(.5));
    this.inputText = this.add.text(480, 348, '', {
      fontFamily: 'monospace', fontSize: '28px', fontStyle: 'bold', color: '#eaf7ff',
    }).setOrigin(.5);
    this.feedbackText = this.add.text(480, 389, '', {
      fontFamily: 'Arial, sans-serif', fontSize: '16px', color: '#a8c6d2',
    }).setOrigin(.5);
  },

  press(direction) {
    if (direction !== 'left' && direction !== 'right') return;
    const s = this.state;
    s.directionPresses += 1;
    s.friction = Math.max(
      E10_NUMBER_DECODE.tuning.minFriction,
      E10_NUMBER_DECODE.tuning.baseFriction - s.directionPresses * E10_NUMBER_DECODE.tuning.frictionLoss,
    );
    s.feedback = `방향 입력 ${s.directionPresses}회 · 바닥이 더 미끄러워졌습니다.`;
    s.feedbackUntil = this.elapsed + 1.15;
    this.actions += 1;
  },

  action() {
    const s = this.state;
    if (!s.grounded) return;
    s.vy = -E10_NUMBER_DECODE.tuning.jump;
    s.grounded = false;
    this.actions += 1;
    this.sfx('jump');
  },

  enterDigit(digit) {
    const s = this.state;
    s.lastHit = digit;
    s.input += digit;

    if (s.input.length < s.target.length) {
      s.lastHitCorrect = true;
      s.feedback = `입력 ${s.input.length}/4 · ${s.input}`;
      s.feedbackUntil = this.elapsed + 1;
      this.sfx('action');
      return;
    }

    const correct = s.input === s.target;
    s.lastHitCorrect = correct;
    if (!correct) {
      const wrongInput = s.input;
      s.input = '';
      s.mistakes += 1;
      s.feedback = `오답 ${wrongInput} · 입력값이 초기화되었습니다.`;
      s.feedbackUntil = this.elapsed + 1.2;
      this.bump();
      return;
    }

    this.sfx('action');
    this.finish(true, `CODE ${s.target} 해독`);
  },

  update(dt) {
    const s = this.state;
    const t = E10_NUMBER_DECODE.tuning;
    const axis = this.axis('left', 'right');
    const traction = E10_NUMBER_DECODE.traction(s);
    if (axis) s.vx = MINI.clamp(s.vx + axis * t.acceleration * traction * dt, -t.maxSpeed, t.maxSpeed);
    else s.vx = moveTowardZero(s.vx, s.friction * dt);

    s.x += s.vx * dt;
    if (s.x < 34 || s.x > 926) {
      s.x = MINI.clamp(s.x, 34, 926);
      s.vx *= -.24;
      this.bump();
    }

    const previousTop = s.y - PLAYER.height / 2;
    s.vy += t.gravity * dt;
    s.y += s.vy * dt;
    const currentTop = s.y - PLAYER.height / 2;

    if (s.vy < 0) {
      const hit = this.digitBlocks.find(block => {
        const bottom = block.y + block.h;
        const overlapsX = s.x + PLAYER.width / 2 > block.x && s.x - PLAYER.width / 2 < block.x + block.w;
        return overlapsX && previousTop >= bottom - 1 && currentTop <= bottom;
      });
      if (hit) {
        s.y = hit.y + hit.h + PLAYER.height / 2 + .5;
        s.vy = 95;
        E10_NUMBER_DECODE.enterDigit.call(this, hit.digit);
      }
    }

    if (s.y + PLAYER.height / 2 >= GROUND_Y && s.vy >= 0) {
      s.y = GROUND_Y - PLAYER.height / 2;
      s.vy = 0;
      s.grounded = true;
    } else {
      s.grounded = false;
    }

    this.anomaly = `마찰 ${Math.round(s.friction)} · 가속력 ${Math.round(traction * 100)}% · 오답 ${s.mistakes}회`;
    this.risk = (t.baseFriction - s.friction) / (t.baseFriction - t.minFriction) * 100;
  },

  render() {
    const s = this.state;
    MINI.frame(this, `AI READ ERROR    TARGET 4 DIGITS    INPUT ${s.input.length}/4`);

    MINI.box(this, 347, 157, 266, 74, 0x2b1735, .96);
    MINI.line(this, 358, 218, 602, 218, 0x78e9ff, 1);
    this.scribbleInk.clear();
    this.targetScribbles.forEach(stroke => {
      this.scribbleInk.lineStyle(stroke.width, stroke.color, .94).lineBetween(stroke.x1, stroke.y1, stroke.x2, stroke.y2);
    });

    this.digitBlocks.forEach((block, index) => {
      const active = s.lastHit === block.digit && this.elapsed <= s.feedbackUntil;
      const color = active ? (s.lastHitCorrect ? 0x93fca0 : 0xff6f8f) : 0xf4c76b;
      MINI.box(this, block.x, block.y, block.w, block.h, color, active ? 1 : .88);
      MINI.line(this, block.x + 5, block.y + block.h, block.x + block.w - 5, block.y + block.h, 0xffffff, .8);
      this.blockLabels[index].setColor(active && !s.lastHitCorrect ? '#fff4f7' : '#102536');
    });

    MINI.box(this, 333, 324, 294, 49, 0x16384b, .94);
    const shown = Array.from({ length: 4 }, (_, index) => s.input[index] ?? '＿').join(' ');
    this.inputText.setText(shown);
    this.feedbackText.setText(this.elapsed <= s.feedbackUntil ? s.feedback : '목표 숫자를 왼쪽부터 차례로 입력하세요.');
    this.feedbackText.setColor(this.elapsed <= s.feedbackUntil && !s.lastHitCorrect ? '#ff9bb7' : '#a8c6d2');

    MINI.box(this, 22, GROUND_Y, 916, 12, 0x557073);
    const speed = Math.abs(s.vx);
    if (speed > 25) {
      const direction = Math.sign(s.vx);
      for (let index = 0; index < 4; index++) {
        const trailX = s.x - direction * (25 + index * 16);
        MINI.line(this, trailX, s.y + 12 + index * 2, trailX - direction * (12 + speed / 30), s.y + 12 + index * 2, 0x8cecff, 1);
      }
    }
    MINI.actor(this, 'player', 'player', s.x, s.y, PLAYER.width, PLAYER.height, MINI.clamp(s.vx / 700, -.22, .22));
    MINI.meter(this, s.input.length / s.target.length);
  },
};


/* Source: stages/index.mjs */
const STAGE_GAMES = Object.freeze({
  e1: E1_GRAVITY_DASH, e2: E2_BOUNCE_BALL, e3: E3_HUMAN_STACK,
  e4: E4_ACCELERATION_DASH, e5: E5_SLINGSHOT, e6: E6_GRAVITY_FLIGHT,
  e7: E7_ROULETTE, e8: E8_SEESAW, e9: E9_ICE_CURLING,
  e10: E10_NUMBER_DECODE,
});


/* Source: game.mjs */

window.archiveAudio = audio;
let progressStorage = null;
try { progressStorage = window.localStorage; } catch { /* 세션 저장만 사용 */ }
window.archiveProgress = createProgressStore(STAGES.map(stage => stage.id), progressStorage);
window.archiveRun = createArchiveRunState(STAGES.map(stage => stage.id));
window.archiveRecords = createMinigameRecords(STAGES.map(stage => stage.id), progressStorage);
/* 미니게임 도감(js/ui/codex-flow.js)이 읽는 "해 본 게임" 기록. */
window.archivePlays = createMinigamePlayLog(STAGES.map(stage => stage.id), progressStorage);
window.addEventListener('archive-sfx', event => audio.play(event.detail?.name));

class ArchiveGame extends Phaser.Scene {
  constructor() {
    super('archive-game'); this.mode = 'idle'; this.pausedByMenu = false;
    this.settings = { shake: true, effects: true }; this.touch = new Set(); this.pointerId = null;
  }
  preload() {
    for (const [id, roles] of Object.entries(globalThis.MINIGAME_ASSETS ?? {})) {
      for (const [role, path] of Object.entries(roles)) if (path) this.load.image(`${id}:${role}`, path);
    }
  }
  create() {
    this.keys = this.input.keyboard.addKeys({ left: 'A', right: 'D', up: 'W', down: 'S', action: 'SPACE', arrowLeft: 'LEFT', arrowRight: 'RIGHT', arrowUp: 'UP', arrowDown: 'DOWN' });
    const directions = { KeyA: 'left', ArrowLeft: 'left', KeyD: 'right', ArrowRight: 'right', KeyW: 'up', ArrowUp: 'up', KeyS: 'down', ArrowDown: 'down' };
    this.input.keyboard.on('keydown', event => {
      if (event.repeat || !this.playable()) return;
      if (event.code === 'Space') this.primaryAction();
      else if (directions[event.code]) this.stageGame.press?.call(this, directions[event.code]);
    });
    this.input.on('pointerdown', p => {
      if (!this.playable() || this.pointerId !== null || p.button > 0) return;
      this.pointerId = p.id; this.pointerAction(p.x, p.y);
    });
    this.input.on('pointermove', p => { if (this.playable() && this.pointerId === p.id) this.stageGame.pointerMove?.call(this, p.x, p.y); });
    const up = p => {
      if (this.pointerId !== p.id) return;
      if (this.playable()) this.stageGame.pointerUp?.call(this, p.x, p.y);
      this.pointerId = null;
    };
    this.input.on('pointerup', up); this.input.on('pointerupoutside', up);
    this.game.canvas.addEventListener('contextmenu', event => event.preventDefault());
    this.game.events.on(Phaser.Core.Events.BLUR, () => {
      this.clearInput();
      if (this.playable()) window.dispatchEvent(new CustomEvent('archive-auto-pause'));
    });
    this.game.canvas.addEventListener('pointercancel', () => this.clearInput());
    window.archiveGame = {
      loadStage: id => this.loadStage(id), start: () => this.startStage(), stop: () => this.stopGame(),
      press: direction => this.directionPress(direction), release: direction => this.directionRelease(direction),
      action: () => { if (!this.touch.has('action')) { this.touch.add('action'); this.primaryAction(); } },
      pause: value => { this.pausedByMenu = Boolean(value); this.clearInput(); },
      applySettings: value => { this.settings = value; },
    };
    window.dispatchEvent(new CustomEvent('archive-game-ready', { detail: { scene: this, stages: STAGES } }));
  }
  playable() { return this.mode === 'playing' && !this.pausedByMenu; }
  held(name) {
    const alias = { left: 'arrowLeft', right: 'arrowRight', up: 'arrowUp', down: 'arrowDown' };
    return this.touch.has(name) || Boolean(this.keys[name]?.isDown || this.keys[alias[name]]?.isDown);
  }
  axis(negative, positive) { return Number(this.held(positive)) - Number(this.held(negative)); }
  clearInput() {
    this.touch.clear(); this.pointerId = null;
    if (this.state) this.stageGame?.cancelInput?.call(this);
    this.input.keyboard?.resetKeys();
  }
  loadStage(id) {
    if (!STAGE_GAMES[id]) throw new Error(`Unknown stage: ${id}`);
    this.clearInput(); this.stageGame?.dispose?.call(this);
    this.ink?.clearMask(true); this.fieldMask?.destroy();
    this.children.removeAll(true); this.tweens.killAll(); this.time.removeAllEvents(); this.cameras.main.resetFX();
    this.stageGame = STAGE_GAMES[id]; this.stageId = id; this.stage = STAGES.find(stage => stage.id === id);
    // 제한시간은 판마다 다시 묻는다 — QA 모드가 20.26초를 바꿔 둘 수 있다(js/config/qa.js).
    this.timeLimit = globalThis.archiveStageTimeLimit?.() ?? 20.26;
    this.mode = 'ready'; this.pausedByMenu = false; this.elapsed = 0; this.remaining = this.timeLimit; this.accumulator = 0;
    this.state = null; this.anomaly = this.stage.anomaly; this.cameras.main.setBackgroundColor('#07141d');
    this.stageGame.build.call(this); this.stageGame.render.call(this); this.sendHud();
  }
  startStage() {
    if (!this.stageId) return;
    if (this.mode !== 'ready') this.loadStage(this.stageId);
    this.mode = 'playing'; this.sfx('click');
  }
  stopGame() {
    this.clearInput(); this.mode = 'idle'; this.pausedByMenu = false; this.stageGame?.dispose?.call(this);
    this.tweens.killAll(); this.time.removeAllEvents(); this.cameras.main.resetFX();
  }
  directionPress(direction) {
    if (!this.playable()) return;
    if (!this.touch.has(direction)) this.stageGame.press?.call(this, direction);
    this.touch.add(direction);
  }
  directionRelease(direction) { this.touch.delete(direction); }
  primaryAction() { if (this.playable()) this.stageGame.action?.call(this); }
  pointerAction(x, y) { if (this.playable()) this.stageGame.pointerDown?.call(this, x, y); }
  sfx(name) { audio.play(name === 'jump' ? 'action' : name); }
  bump() { this.sfx('hit'); if (this.settings.shake) this.cameras.main.shake(100, .004); }
  sendHud() {
    window.dispatchEvent(new CustomEvent('archive-hud', { detail: { remaining: this.remaining, timeLimit: this.timeLimit, actions: this.actions, anomaly: this.anomaly, risk: this.risk } }));
  }
  update(_time, deltaMs) {
    if (!this.playable()) return;
    // 120Hz 공통 물리 스텝. 타이머와 물리가 같은 시간을 소비하도록 프레임을 분할합니다.
    this.accumulator += Math.max(0, deltaMs) / 1000;
    const step = 1 / 120;
    while (this.accumulator >= step && this.playable()) {
      this.accumulator -= step;
      const dt = Math.min(step, this.remaining);
      this.elapsed += dt; this.remaining = Math.max(0, this.timeLimit - this.elapsed);
      window.dispatchEvent(new CustomEvent('archive-play-time', { detail: { deltaMs: dt * 1000 } }));
      this.stageGame.update.call(this, dt);
      if (this.playable() && this.remaining <= .000001) this.finish(Boolean(this.stageGame.timeout?.call(this)), `${this.timeLimit.toFixed(2)}초 종료`);
    }
    this.stageGame.render.call(this); this.sendHud();
  }
  finish(success, extra = '') {
    if (!this.playable()) return;
    this.mode = 'done'; this.clearInput(); this.sfx(success ? 'success' : 'failure');
    if (this.settings.effects) this.cameras.main.flash(150, success ? 130 : 255, success ? 255 : 95, success ? 170 : 110);
    window.dispatchEvent(new CustomEvent('archive-stage-end', { detail: { success, elapsed: this.elapsed, timeLimit: this.timeLimit, actions: this.actions, extra } }));
  }
}

window.archivePhaserGame = new Phaser.Game({
  type: Phaser.AUTO, width: 960, height: 540, parent: 'game-container', backgroundColor: '#07141d',
  render: { antialias: true }, scale: { mode: Phaser.Scale.FIT, autoCenter: Phaser.Scale.CENTER_BOTH }, scene: ArchiveGame,
});

})();
