/*
 * Generated by scripts/build-archive-classic.ps1.
 * This classic-script bundle mirrors js/archive/*.mjs so index.html also works
 * when opened directly through file://, where browsers block ES module imports.
 */
(function () {
/* Source: data.mjs */
const GAME_TITLE = "2026 ARCHIVE";

const PROLOGUE = [
  {
    code: "SYSTEM // 00:00:01",
    title: "2026년의 마지막 백업이 열렸다.",
    body: "한 해의 장면을 보관하던 2026 ARCHIVE. 새벽 0시, 보존 서버의 물리 인덱스가 동시에 붕괴했다.",
  },
  {
    code: "EMERGENCY // RECORD DECAY",
    title: "손상된 기록은 20.26초만 유지된다.",
    body: "기록이 재생되는 동안 직접 개입해 마지막 장면을 완성해야 한다. 그러나 입력이 많아질수록 오류는 더 강해진다.",
  },
  {
    code: "OPERATOR // ASSIGNED",
    title: "당신은 마지막 기록 관리자다.",
    body: "속도, 중력, 탄성, 반동, 마찰, 빛, 회전. 일곱 개의 물리 채널을 최소한의 개입으로 복구하라.",
  },
];

const STAGES = [
  {
    id: "maze",
    recordSymbol: "↗",
    number: "01",
    code: "VELOCITY_INDEX",
    title: "가속 코스",
    objective: "공을 RESTORE 구역에서 저속으로 안정시키세요.",
    anomaly: "방향 입력마다 가속 · 강한 벽 충돌 −1초",
    controls: "WASD / 방향키 · 반대 방향으로 제동",
    actionLabel: "방향 입력",
    logTitle: "속도 채널 복구",
    log: "첫 기록은 빨라지는 것보다 멈추는 법을 기억하고 있었다. 복구율 14%.",
  },
  {
    id: "gravity",
    recordSymbol: "↓",
    number: "02",
    code: "GRAVITY_STACK",
    title: "중력 타워",
    objective: "네 개의 발판을 올라 상단 비콘에 접촉하세요.",
    anomaly: "점프할 때마다 중력이 강해져 다음 점프가 낮아집니다.",
    controls: "A/D 또는 ←/→ 이동 · Space 점프",
    actionLabel: "점프",
    logTitle: "중력 채널 복구",
    log: "기록은 위로 향할수록 무거워졌다. 필요한 점프만 남기자 길이 열렸다. 복구율 28%.",
  },
  {
    id: "bounce",
    recordSymbol: "◉",
    number: "03",
    code: "RESTITUTION_LOOP",
    title: "탄성 우회",
    objective: "공을 발사해 차단벽 너머의 코어에 넣으세요.",
    anomaly: "충돌할 때마다 탄성이 증가해 더 빠르게 튕깁니다.",
    controls: "마우스 클릭 / 터치로 발사 방향 지정",
    actionLabel: "충돌",
    logTitle: "탄성 채널 복구",
    log: "충격은 사라지지 않고 다음 충격을 키웠다. 한 번의 정확한 반사가 기록을 고정했다. 복구율 42%.",
  },
  {
    id: "recoil",
    recordSymbol: "⌖",
    number: "04",
    code: "RECOIL_ARRAY",
    title: "반동 사격장",
    objective: "이동하는 세 개의 기록 노드를 모두 맞히세요.",
    anomaly: "발사할 때마다 포대가 밀리고 조준 오차가 커집니다.",
    controls: "마우스 / 터치로 조준 · 클릭하여 발사",
    actionLabel: "발사",
    logTitle: "반동 채널 복구",
    log: "모든 발사는 기록 관리자를 뒤로 밀어냈다. 적은 탄환이 가장 정확한 답이었다. 복구율 57%.",
  },
  {
    id: "friction",
    recordSymbol: "≈",
    number: "05",
    code: "FRICTION_DROP",
    title: "무마찰 배송",
    objective: "화물을 장애물 사이로 운반해 적재 구역에 정지시키세요.",
    anomaly: "이동 입력이 쌓일수록 마찰력이 감소합니다.",
    controls: "WASD / 방향키 · 반대 방향으로 제동",
    actionLabel: "이동 입력",
    logTitle: "마찰 채널 복구",
    log: "미끄러지는 기록은 목적지를 지나치고도 멈추지 않았다. 움직임보다 제동이 중요했다. 복구율 71%.",
  },
  {
    id: "darkness",
    recordSymbol: "☼",
    number: "06",
    code: "LIGHT_DECAY",
    title: "소실 회랑",
    objective: "시야가 사라지기 전에 출구 비콘에 도착하세요.",
    anomaly: "방향을 새로 누를 때마다 조명 반경이 줄어듭니다.",
    controls: "WASD / 방향키",
    actionLabel: "방향 입력",
    logTitle: "광원 채널 복구",
    log: "기록은 볼 수 없는 곳에서도 존재했다. 경로를 먼저 읽은 뒤 움직이자 빛이 돌아왔다. 복구율 85%.",
  },
  {
    id: "rotation",
    recordSymbol: "↻",
    number: "07",
    code: "ANGULAR_LOCK",
    title: "각속도 잠금",
    objective: "회전 바를 목표 각도에 맞추고 정지시키세요.",
    anomaly: "회전 입력마다 각속도와 토크가 증가합니다.",
    controls: "A/D 또는 ←/→ 회전 · 반대 방향으로 제동",
    actionLabel: "회전 입력",
    logTitle: "최종 채널 복구",
    log: "마지막 기록은 계속 돌고 있었다. 더 돌리는 대신 정확한 순간에 힘을 거두자 정지했다. 복구율 100%.",
  },
];

const ENDING = {
  code: "ARCHIVE // STABLE",
  title: "2026년의 기록이 다시 재생된다.",
  body: "오류의 원인은 외부 침입이 아니었다. 기록을 완벽하게 고치려는 수많은 개입이 물리 인덱스를 뒤틀고 있었다. 당신은 최소한의 행동으로 시스템을 안정시켰다. 이제 보존된 장면들은 다음 기록 관리자를 기다린다.",
};

const STORAGE_KEY = "archive-2026-progress-v1";
const SETTINGS_KEY = "archive-2026-settings-v1";




/* Source: audio.mjs */
class ArchiveAudio {
  constructor() {
    this.context = null;
    this.volume = 0.55;
  }

  setVolume(value) {
    this.volume = Math.max(0, Math.min(1, Number(value)));
  }

  ensureContext() {
    if (!this.context) {
      const AudioContext = window.AudioContext || window.webkitAudioContext;
      if (AudioContext) this.context = new AudioContext();
    }
    if (this.context?.state === "suspended") this.context.resume();
    return this.context;
  }

  tone(frequency, duration = 0.08, type = "sine", gain = 0.12, slide = 0) {
    if (this.volume <= 0) return;
    const context = this.ensureContext();
    if (!context) return;
    const now = context.currentTime;
    const oscillator = context.createOscillator();
    const amplifier = context.createGain();
    oscillator.type = type;
    oscillator.frequency.setValueAtTime(frequency, now);
    if (slide) oscillator.frequency.exponentialRampToValueAtTime(Math.max(30, frequency + slide), now + duration);
    amplifier.gain.setValueAtTime(Math.max(0.0001, gain * this.volume), now);
    amplifier.gain.exponentialRampToValueAtTime(0.0001, now + duration);
    oscillator.connect(amplifier).connect(context.destination);
    oscillator.start(now);
    oscillator.stop(now + duration);
  }

  play(name) {
    if (name === "click") this.tone(420, 0.05, "square", 0.05, 90);
    if (name === "action") this.tone(260, 0.06, "triangle", 0.055, 65);
    if (name === "warning") this.tone(150, 0.11, "sawtooth", 0.065, -35);
    if (name === "hit") this.tone(620, 0.09, "square", 0.055, 250);
    if (name === "success") {
      this.tone(440, 0.16, "sine", 0.07, 220);
      window.setTimeout(() => this.tone(660, 0.22, "sine", 0.07, 220), 90);
    }
    if (name === "failure") this.tone(210, 0.3, "sawtooth", 0.06, -100);
  }
}

const audio = new ArchiveAudio();




/* Source: level-data.mjs */
const VIEWPORT = { width: 960, height: 540 };
const BALL_RADIUS = 12;
const START = { x: 100, y: 450 };
const GOAL = { x: 715, y: 420, radius: 30 };

const PHYSICS = {
  timeLimit: 20.26,
  baseAcceleration: 610,
  baseMaxSpeed: 190,
  maxMultiplier: 3.35,
  goalMaxSpeed: 110,
  goalHoldSeconds: 0.35,
  wallPenaltySeconds: 1,
  wallImpactMinSpeed: 90,
  wallImpactCooldown: 0.45,
};

// Record 01: four broad S-bends, then an optional loop around the side island.
// Alternating dividers make the bends real without tightening the first turns.
const WALLS = [
  { x: 32, y: 126, w: 896, h: 14, kind: "outer" },
  { x: 32, y: 498, w: 896, h: 14, kind: "outer" },
  { x: 32, y: 126, w: 14, h: 386, kind: "outer" },
  { x: 914, y: 126, w: 14, h: 386, kind: "outer" },
  { x: 46, y: 140, w: 164, h: 212, kind: "divider" },
  { x: 400, y: 290, w: 25, h: 208, kind: "divider" },
  { x: 610, y: 140, w: 25, h: 212, kind: "divider" },
  { x: 775, y: 295, w: 25, h: 45, kind: "divider" },
];

const ROUTE = [
  { x: 300, y: 450, input: "right" },
  { x: 300, y: 215, input: "up" },
  { x: 515, y: 215, input: "right" },
  { x: 515, y: 420, input: "down" },
  { ...GOAL, input: "right" },
];
const FRAGMENT_ROUTE = [
  ...ROUTE.slice(0, 4),
  { x: 840, y: 420, input: "right" },
  { x: 840, y: 210, input: "up" },
  { x: 715, y: 210, input: "left" },
  { ...GOAL, input: "down" },
];


/* Source: physics-core.mjs */

const DIRECTION_VECTORS = {
  left: { x: -1, y: 0 },
  right: { x: 1, y: 0 },
  up: { x: 0, y: -1 },
  down: { x: 0, y: 1 },
};

function multiplierForPresses(presses) {
  if (presses <= 0) return 1;
  if (presses <= 3) return 1 + (presses - 1) * 0.08;
  if (presses <= 7) return 1.42 + (presses - 4) * 0.29;
  return Math.min(PHYSICS.maxMultiplier, 2.66 + (presses - 8) * 0.22);
}

function dragForPresses(presses) {
  if (presses <= 3) return 920;
  if (presses <= 7) return Math.max(260, 710 - (presses - 3) * 105);
  return Math.max(90, 250 - (presses - 7) * 28);
}

function createBallState() {
  return {
    x: START.x,
    y: START.y,
    vx: 0,
    vy: 0,
    input: null,
    presses: 0,
    multiplier: 1,
    collisions: 0,
    touchingWall: false,
    wallContacts: new Set(),
    impactCooldown: 0,
  };
}

function registerDirection(state, direction) {
  if (!DIRECTION_VECTORS[direction]) return;
  state.input = direction;
  state.presses += 1;
  state.multiplier = multiplierForPresses(state.presses);
}

function releaseDirection(state, direction) {
  if (state.input === direction) state.input = null;
}

function physicsMoveTowardZero(value, amount) {
  if (Math.abs(value) <= amount) return 0;
  return value - Math.sign(value) * amount;
}

function resolveCircleRect(state, rect) {
  const nearestX = Math.max(rect.x, Math.min(state.x, rect.x + rect.w));
  const nearestY = Math.max(rect.y, Math.min(state.y, rect.y + rect.h));
  let dx = state.x - nearestX;
  let dy = state.y - nearestY;
  const radiusSq = BALL_RADIUS * BALL_RADIUS;
  let distanceSq = dx * dx + dy * dy;

  if (distanceSq >= radiusSq) return null;

  let nx;
  let ny;
  let penetration;

  if (distanceSq > 0.0001) {
    const distance = Math.sqrt(distanceSq);
    nx = dx / distance;
    ny = dy / distance;
    penetration = BALL_RADIUS - distance;
  } else {
    const toLeft = Math.abs(state.x - rect.x);
    const toRight = Math.abs(rect.x + rect.w - state.x);
    const toTop = Math.abs(state.y - rect.y);
    const toBottom = Math.abs(rect.y + rect.h - state.y);
    const minimum = Math.min(toLeft, toRight, toTop, toBottom);
    nx = minimum === toLeft ? -1 : minimum === toRight ? 1 : 0;
    ny = minimum === toTop ? -1 : minimum === toBottom ? 1 : 0;
    penetration = BALL_RADIUS + minimum;
  }

  state.x += nx * penetration;
  state.y += ny * penetration;

  const velocityIntoWall = state.vx * nx + state.vy * ny;
  if (velocityIntoWall < 0) {
    state.vx -= velocityIntoWall * nx;
    state.vy -= velocityIntoWall * ny;
  }
  return Math.max(0, -velocityIntoWall);
}

function stepBall(state, dt, walls = WALLS) {
  state.impactCooldown = Math.max(0, state.impactCooldown - dt);
  const vector = DIRECTION_VECTORS[state.input] ?? { x: 0, y: 0 };
  const acceleration = PHYSICS.baseAcceleration * state.multiplier;
  const drag = dragForPresses(state.presses);

  if (vector.x !== 0) state.vx += vector.x * acceleration * dt;
  else state.vx = physicsMoveTowardZero(state.vx, drag * dt);

  if (vector.y !== 0) state.vy += vector.y * acceleration * dt;
  else state.vy = physicsMoveTowardZero(state.vy, drag * dt);

  const maxSpeed = PHYSICS.baseMaxSpeed * state.multiplier;
  const speed = Math.hypot(state.vx, state.vy);
  if (speed > maxSpeed) {
    state.vx = (state.vx / speed) * maxSpeed;
    state.vy = (state.vy / speed) * maxSpeed;
  }

  state.x += state.vx * dt;
  state.y += state.vy * dt;

  let frameCollisions = 0;
  let newImpactSpeed = 0;
  for (let pass = 0; pass < 3; pass += 1) {
    let resolved = false;
    for (const wall of walls) {
      const impactSpeed = resolveCircleRect(state, wall);
      if (impactSpeed !== null) {
        resolved = true;
        frameCollisions += 1;
        if (!state.wallContacts.has(wall)) newImpactSpeed = Math.max(newImpactSpeed, impactSpeed);
      }
    }
    if (!resolved) break;
  }
  if (newImpactSpeed >= PHYSICS.wallImpactMinSpeed && state.impactCooldown <= 0) {
    state.collisions += 1;
    state.impactCooldown = PHYSICS.wallImpactCooldown;
  }
  // Exact edge contact stays latched until the ball actually leaves the wall.
  state.wallContacts = new Set(walls.filter((wall) => {
    const nearX = Math.max(wall.x, Math.min(state.x, wall.x + wall.w));
    const nearY = Math.max(wall.y, Math.min(state.y, wall.y + wall.h));
    return Math.hypot(state.x - nearX, state.y - nearY) <= BALL_RADIUS + 0.5;
  }));
  state.touchingWall = state.wallContacts.size > 0;
  return frameCollisions;
}

function riskLabel(presses) {
  if (presses <= 3) return "안정";
  if (presses <= 7) return "가속";
  if (presses <= 11) return "위험";
  return "붕괴 직전";
}



/* Source: progress.mjs */
const RECORD_STATUS = Object.freeze({
  DAMAGED: "DAMAGED", PARTIAL: "PARTIALLY RESTORED", FULL: "FULLY RESTORED", LOST: "RECORD LOST",
});
const PROGRESS_KEY = "archive-2026-recovery-v1";
const RECOVERY_RULES = Object.freeze({ partialWeight: 0.5, normalEndingRatio: 0.5 });

// Results belong to an attempt; stored records only ever improve.
function createProgressStore(stageIds, storage = null) {
  const ids = [...new Set(stageIds)];
  const records = Object.fromEntries(ids.map((id) => [id, RECORD_STATUS.DAMAGED]));
  try {
    const saved = JSON.parse(storage?.getItem(PROGRESS_KEY) || "null");
    if (saved?.version === 1) for (const id of ids) {
      if ([RECORD_STATUS.PARTIAL, RECORD_STATUS.FULL].includes(saved.records?.[id])) records[id] = saved.records[id];
    }
  } catch { /* An unavailable or damaged save must not prevent play. */ }
  const summary = () => {
    const clearedCount = ids.filter((id) => records[id] !== RECORD_STATUS.DAMAGED).length;
    const fragmentCount = ids.filter((id) => records[id] === RECORD_STATUS.FULL).length;
    const recoveryRate = ids.length ? Math.round(100 * (fragmentCount + (clearedCount - fragmentCount) * RECOVERY_RULES.partialWeight) / ids.length) : 0;
    const allCleared = ids.length > 0 && clearedCount === ids.length;
    const ending = !allCleared ? null : fragmentCount === ids.length ? "complete"
      : fragmentCount / ids.length >= RECOVERY_RULES.normalEndingRatio ? "normal" : "incomplete";
    return { totalRecords: ids.length, clearedCount, fragmentCount, recoveryRate, allCleared, ending };
  };
  return {
    status: (id) => records[id] || RECORD_STATUS.DAMAGED,
    summary,
    record(id, success, fragmentCollected) {
      if (!ids.includes(id)) throw new Error(`Unknown record: ${id}`);
      const result = !success ? RECORD_STATUS.LOST : fragmentCollected ? RECORD_STATUS.FULL : RECORD_STATUS.PARTIAL;
      if (success && records[id] !== RECORD_STATUS.FULL) {
        records[id] = result;
        try { storage?.setItem(PROGRESS_KEY, JSON.stringify({ version: 1, records })); } catch { /* Session state remains available. */ }
      }
      return { result, savedStatus: records[id], ...summary() };
    },
  };
}


/* Source: fragments.mjs */
// Initial placements only. Change these independently of the physics and maps.
const MEMORY_FRAGMENTS = Object.freeze({
  maze: { x: 830, y: 210, radius: 14, hint: "오른쪽 위 조각을 얻고 돌아오기" },
  gravity: { x: 85, y: 387, radius: 12, hint: "첫 발판 왼쪽의 조각에 접촉" },
  bounce: { x: 550, y: 400, radius: 14, hint: "공으로 조각에 접촉" },
  recoil: { x: 100, y: 280, radius: 16, hint: "세 노드 완료 전에 조각을 사격" },
  friction: { x: 440, y: 105, radius: 12, hint: "화물로 상단 조각에 접촉" },
  darkness: { x: 610, y: 290, radius: 12, hint: "회랑 안쪽의 조각에 접촉" },
  rotation: { x: 480 + Math.cos(-2.1) * 165, y: 272 + Math.sin(-2.1) * 165, radius: 14, hint: "밝은 끝점을 조각까지 회전" },
});

// Swept circle check prevents fast projectiles from skipping small fragments.
function touchesFragment(fragment, body, previous = body) {
  const dx = body.x - previous.x;
  const dy = body.y - previous.y;
  const length = dx * dx + dy * dy;
  const t = length ? Math.max(0, Math.min(1, ((fragment.x - previous.x) * dx + (fragment.y - previous.y) * dy) / length)) : 0;
  const radius = fragment.radius + (body.radius ?? 12);
  return Math.hypot(fragment.x - previous.x - dx * t, fragment.y - previous.y - dy * t) <= radius;
}


/* Source: game.mjs */

const WIDTH = VIEWPORT.width;
const HEIGHT = VIEWPORT.height;
const lightOverlay = document.querySelector("#light-overlay");
const corruptionOverlay = document.querySelector("#corruption");

window.archiveAudio = audio;
let progressStorage = null;
try { progressStorage = window.localStorage; } catch { /* Session-only fallback. */ }
window.archiveProgress = createProgressStore(STAGES.map((stage) => stage.id), progressStorage);
window.addEventListener("archive-sfx", (event) => audio.play(event.detail?.name));

const clamp = (value, minimum, maximum) => Math.max(minimum, Math.min(maximum, value));
const moveTowardZero = (value, amount) => Math.abs(value) <= amount ? 0 : value - Math.sign(value) * amount;
const distance = (a, b) => Math.hypot(a.x - b.x, a.y - b.y);

function emit(name, detail) {
  window.dispatchEvent(new CustomEvent(name, { detail }));
}

function circleRectCollision(body, rect, restitution = 0) {
  const radius = body.radius;
  const nearestX = clamp(body.x, rect.x, rect.x + rect.w);
  const nearestY = clamp(body.y, rect.y, rect.y + rect.h);
  let dx = body.x - nearestX;
  let dy = body.y - nearestY;
  const distanceSquared = dx * dx + dy * dy;
  if (distanceSquared >= radius * radius) return false;

  let nx;
  let ny;
  let penetration;
  if (distanceSquared > 0.0001) {
    const length = Math.sqrt(distanceSquared);
    nx = dx / length;
    ny = dy / length;
    penetration = radius - length;
  } else {
    const sides = [
      { d: Math.abs(body.x - rect.x), nx: -1, ny: 0 },
      { d: Math.abs(rect.x + rect.w - body.x), nx: 1, ny: 0 },
      { d: Math.abs(body.y - rect.y), nx: 0, ny: -1 },
      { d: Math.abs(rect.y + rect.h - body.y), nx: 0, ny: 1 },
    ].sort((a, b) => a.d - b.d);
    ({ nx, ny } = sides[0]);
    penetration = radius + sides[0].d;
  }

  body.x += nx * penetration;
  body.y += ny * penetration;
  const dot = body.vx * nx + body.vy * ny;
  if (dot < 0) {
    body.vx -= (1 + restitution) * dot * nx;
    body.vy -= (1 + restitution) * dot * ny;
  }
  return true;
}

function boundaryWalls(inset = 30, thickness = 14) {
  return [
    { x: inset, y: inset, w: WIDTH - inset * 2, h: thickness },
    { x: inset, y: HEIGHT - inset - thickness, w: WIDTH - inset * 2, h: thickness },
    { x: inset, y: inset, w: thickness, h: HEIGHT - inset * 2 },
    { x: WIDTH - inset - thickness, y: inset, w: thickness, h: HEIGHT - inset * 2 },
  ];
}

class ArchiveGame extends Phaser.Scene {
  constructor() {
    super("archive-game");
    this.stageId = null;
    this.mode = "idle";
    this.remaining = PHYSICS.timeLimit;
    this.settings = window.archiveSettings || { shake: true, effects: true };
    this.pausedByMenu = false;
  }

  create() {
    const codes = Phaser.Input.Keyboard.KeyCodes;
    this.keys = {
      up: [this.input.keyboard.addKey(codes.W), this.input.keyboard.addKey(codes.UP)],
      down: [this.input.keyboard.addKey(codes.S), this.input.keyboard.addKey(codes.DOWN)],
      left: [this.input.keyboard.addKey(codes.A), this.input.keyboard.addKey(codes.LEFT)],
      right: [this.input.keyboard.addKey(codes.D), this.input.keyboard.addKey(codes.RIGHT)],
      action: this.input.keyboard.addKey(codes.SPACE),
    };
    this.input.keyboard.addCapture([codes.W, codes.A, codes.S, codes.D, codes.UP, codes.DOWN, codes.LEFT, codes.RIGHT, codes.SPACE]);
    this.input.on("pointerdown", (pointer) => {
      if (this.mode === "playing" && !this.pausedByMenu) this.pointerAction(pointer.worldX, pointer.worldY);
    });

    window.archiveGame = {
      loadStage: (id) => this.loadStage(id),
      start: () => this.startStage(),
      press: (direction) => this.directionPress(direction),
      release: (direction) => this.directionRelease(direction),
      action: () => this.primaryAction(),
      pause: (value) => { this.pausedByMenu = Boolean(value); },
      stop: () => this.stopGame(),
      applySettings: (value) => { this.settings = value; },
    };
    emit("archive-game-ready", { scene: this, stages: STAGES });
  }

  loadStage(id) {
    this.stageId = id;
    this.mode = "ready";
    this.remaining = PHYSICS.timeLimit;
    this.elapsed = 0;
    this.timePenalty = 0;
    this.pausedByMenu = false;
    this.children.removeAll(true);
    this.tweens.killAll();
    this.cameras.main.resetFX();
    this.cameras.main.setBackgroundColor("#07141d");
    corruptionOverlay.style.opacity = "0";
    lightOverlay.classList.remove("is-active");
    this.drawBackdrop();
    const builders = {
      maze: () => this.buildMaze(),
      gravity: () => this.buildGravity(),
      bounce: () => this.buildBounce(),
      recoil: () => this.buildRecoil(),
      friction: () => this.buildFriction(),
      darkness: () => this.buildDarkness(),
      rotation: () => this.buildRotation(),
    };
    builders[id]?.();
    this.buildFragment();
    this.sendHud();
  }

  startStage() {
    if (!this.stageId) return;
    this.loadStage(this.stageId);
    this.mode = "playing";
    this.remaining = PHYSICS.timeLimit;
    emit("archive-sfx", { name: "click" });
  }

  stopGame() {
    this.mode = "idle";
    this.pausedByMenu = false;
    this.setCorruption(0);
    lightOverlay.classList.remove("is-active");
  }

  drawBackdrop() {
    const grid = this.add.graphics();
    grid.lineStyle(1, 0x153746, 0.34);
    for (let x = 32; x < WIDTH; x += 32) grid.lineBetween(x, 0, x, HEIGHT);
    for (let y = 28; y < HEIGHT; y += 32) grid.lineBetween(0, y, WIDTH, y);
    this.add.text(24, 18, "ARCHIVE SIMULATION SPACE", {
      fontFamily: "monospace",
      fontSize: "11px",
      color: "#315a6c",
    }).setDepth(1);
  }

  drawWalls(walls, color = 0x205568, stroke = 0x55b7ce) {
    const graphics = this.add.graphics();
    for (const wall of walls) {
      graphics.fillStyle(color, 1).fillRect(wall.x, wall.y, wall.w, wall.h);
      graphics.lineStyle(1, stroke, 0.55).strokeRect(wall.x + 1, wall.y + 1, wall.w - 2, wall.h - 2);
    }
    return graphics;
  }

  drawGoal(x, y, radius = 25, label = "RESTORE") {
    const ring = this.add.circle(x, y, radius, 0x93fca0, 0.1).setStrokeStyle(3, 0x93fca0, 0.92).setDepth(3);
    this.add.circle(x, y, 5, 0xc8ffd0, 0.92).setDepth(3);
    this.add.text(x, y + radius + 10, label, { fontFamily: "monospace", fontSize: "10px", color: "#93fca0" }).setOrigin(0.5).setDepth(3);
    this.tweens.add({ targets: ring, scale: 1.15, alpha: 0.35, yoyo: true, repeat: -1, duration: 760 });
    return ring;
  }

  shake(duration, intensity) {
    if (this.settings.shake) this.cameras.main.shake(duration, intensity);
  }

  flash(duration, r, g, b) {
    if (this.settings.effects) this.cameras.main.flash(duration, r, g, b, false);
  }

  setCorruption(risk) {
    corruptionOverlay.style.opacity = this.settings.effects ? String(clamp(risk / 230, 0, 0.48)) : "0";
  }

  sendHud() {
    emit("archive-hud", {
      remaining: this.remaining,
      actions: this.actions ?? 0,
      anomaly: this.anomaly ?? "대기",
      risk: this.risk ?? 0,
      fragmentCollected: this.fragmentCollected,
      fragmentHint: this.fragment?.hint,
      wallHits: this.stageId === "maze" ? this.state.ball.collisions : null,
      timePenalty: this.timePenalty,
    });
  }

  readKeyboard() {
    const groups = [["up", this.keys.up], ["down", this.keys.down], ["left", this.keys.left], ["right", this.keys.right]];
    for (const [direction, keys] of groups) {
      for (const key of keys) {
        if (Phaser.Input.Keyboard.JustDown(key)) this.directionPress(direction);
        if (Phaser.Input.Keyboard.JustUp(key)) this.directionRelease(direction);
      }
    }
    if (Phaser.Input.Keyboard.JustDown(this.keys.action)) this.primaryAction();
  }

  update(_time, deltaMs) {
    this.readKeyboard();
    if (this.mode !== "playing" || this.pausedByMenu) return;
    const dt = Math.min(deltaMs / 1000, 0.025);
    this.elapsed += Math.min(this.remaining, deltaMs / 1000);
    this.remaining = Math.max(0, this.remaining - deltaMs / 1000);
    if (this.remaining <= 0) { this.finish(false); this.sendHud(); return; }
    const previous = this.fragmentBody();
    const updates = {
      maze: () => this.updateMaze(dt),
      gravity: () => this.updateGravity(dt),
      bounce: () => this.updateBounce(dt),
      recoil: () => this.updateRecoil(dt),
      friction: () => this.updateFriction(dt),
      darkness: () => this.updateDarkness(dt),
      rotation: () => this.updateRotation(dt),
    };
    updates[this.stageId]?.();
    if (this.mode === "playing") this.checkFragment(this.fragmentBody(), previous);
    this.sendHud();
    if (this.remaining <= 0 && this.mode === "playing") this.finish(false);
  }

  directionPress(direction) {
    if (this.mode !== "playing" || this.pausedByMenu) return;
    const handlers = {
      maze: () => this.mazePress(direction),
      gravity: () => this.gravityPress(direction),
      friction: () => this.frictionPress(direction),
      darkness: () => this.darknessPress(direction),
      rotation: () => this.rotationPress(direction),
    };
    handlers[this.stageId]?.();
  }

  directionRelease(direction) {
    if (this.mode !== "playing") return;
    const handlers = {
      maze: () => releaseDirection(this.state.ball, direction),
      gravity: () => { if (this.state.direction === direction) this.state.direction = null; },
      friction: () => { if (this.state.direction === direction) this.state.direction = null; },
      darkness: () => { if (this.state.direction === direction) this.state.direction = null; },
      rotation: () => { if (this.state.direction === direction) this.state.direction = null; },
    };
    handlers[this.stageId]?.();
  }

  primaryAction() {
    if (this.mode !== "playing" || this.pausedByMenu) return;
    if (this.stageId === "gravity") this.gravityJump();
  }

  pointerAction(x, y) {
    if (this.stageId === "bounce") this.launchBounceBall(x, y);
    if (this.stageId === "recoil") this.fireRecoilShot(x, y);
  }

  finish(success, extra = "") {
    if (this.mode !== "playing") return;
    if (success) this.checkFragment(this.fragmentBody());
    this.mode = "done";
    this.setCorruption(0);
    lightOverlay.classList.remove("is-active");
    if (success) this.flash(220, 147, 252, 160);
    emit("archive-stage-end", {
      success,
      elapsed: this.elapsed,
      timePenalty: this.timePenalty,
      actions: this.actions ?? 0,
      extra,
      fragmentCollected: this.fragmentCollected,
    });
  }

  buildFragment() {
    this.fragmentTip = null;
    this.fragment = MEMORY_FRAGMENTS[this.stageId];
    this.fragmentCollected = false;
    this.fragmentObject = this.add.rectangle(this.fragment.x, this.fragment.y, 19, 19, 0xffd27c, 0.85)
      .setStrokeStyle(2, 0xfff0c2).setRotation(Math.PI / 4).setDepth(7);
    this.fragmentRing = this.add.circle(this.fragment.x, this.fragment.y, this.fragment.radius + 7, 0xffd27c, 0.08)
      .setStrokeStyle(1, 0xffd27c, 0.6).setDepth(6);
    this.tweens.add({ targets: this.fragmentRing, alpha: 0.3, duration: 650, yoyo: true, repeat: -1 });
    if (this.stageId === "rotation") this.fragmentTip = this.add.circle(0, 0, 7, 0xffe5ab).setDepth(6);
    this.sendHud();
  }

  fragmentBody() {
    const s = this.state;
    if (!s || this.stageId === "recoil") return null;
    if (this.stageId === "rotation") {
      const body = { x: s.center.x + Math.cos(s.angle) * 165, y: s.center.y + Math.sin(s.angle) * 165, radius: 7 };
      this.fragmentTip?.setPosition(body.x, body.y);
      return body;
    }
    const body = this.stageId === "maze" ? s.ball : s;
    return { x: body.x, y: body.y, radius: body.radius ?? 12 };
  }

  checkFragment(body, previous = body) {
    if (this.mode !== "playing" || this.pausedByMenu || this.fragmentCollected || !body) return;
    if (!touchesFragment(this.fragment, body, previous || body)) return;
    this.fragmentCollected = true;
    this.fragmentObject.setVisible(false);
    this.fragmentRing.setVisible(false);
    emit("archive-sfx", { name: "hit" });
    this.sendHud();
  }

  /* 01 — Velocity maze */
  buildMaze() {
    this.actions = 0;
    this.risk = 0;
    this.anomaly = "안정";
    this.drawWalls(WALLS, 0x164d48, 0x4ca78f);
    this.drawGoal(GOAL.x, GOAL.y, GOAL.radius);
    const guide = this.add.graphics().setDepth(1);
    guide.lineStyle(2, 0x56ddfb, 0.2).beginPath().moveTo(START.x, START.y);
    for (const point of ROUTE) guide.lineTo(point.x, point.y);
    guide.strokePath();
    guide.lineStyle(2, 0xffd27c, 0.2).beginPath().moveTo(GOAL.x, GOAL.y);
    for (const point of FRAGMENT_ROUTE.slice(4)) guide.lineTo(point.x, point.y);
    guide.strokePath();
    this.add.text(175, 405, "HOLD →", { fontFamily: "monospace", fontSize: "13px", color: "#78bdc8" }).setOrigin(0.5);
    this.add.text(300, 365, "TURN ↑", { fontFamily: "monospace", fontSize: "13px", color: "#78bdc8" }).setOrigin(0.5);
    this.add.text(515, 290, "TURN ↓", { fontFamily: "monospace", fontSize: "13px", color: "#78bdc8" }).setOrigin(0.5);
    this.add.text(GOAL.x, GOAL.y - 48, "BRAKE", { fontFamily: "monospace", fontSize: "12px", color: "#93fca0" }).setOrigin(0.5);
    this.add.text(850, 365, "MEMORY ↑", { fontFamily: "monospace", fontSize: "12px", color: "#ffd27c" }).setOrigin(0.5);
    this.add.text(128, 230, "벽 충돌 −1.00초\n반대 방향으로 제동", { fontFamily: "sans-serif", fontSize: "15px", color: "#e1c29a", align: "center", lineSpacing: 8 }).setOrigin(0.5).setDepth(3);
    this.state = {
      ball: createBallState(),
      goalHold: 0,
      wasInside: false,
      overruns: 0,
      trail: [],
    };
    this.trailGraphics = this.add.graphics().setDepth(4);
    this.playerGlow = this.add.circle(START.x, START.y, BALL_RADIUS + 8, 0x56ddfb, 0.13).setDepth(5);
    this.player = this.add.circle(START.x, START.y, BALL_RADIUS, 0xe7fbff, 1).setStrokeStyle(3, 0x56ddfb).setDepth(6);
    this.goalProgress = this.add.graphics().setDepth(5);
    this.goalText = this.add.text(GOAL.x, GOAL.y, "0%", { fontFamily: "monospace", fontSize: "10px", color: "#d9ffdd" }).setOrigin(0.5).setDepth(6);
  }

  mazePress(direction) {
    registerDirection(this.state.ball, direction);
    this.actions = this.state.ball.presses;
    this.risk = clamp((this.state.ball.multiplier - 1) / (PHYSICS.maxMultiplier - 1) * 100, 0, 100);
    this.anomaly = riskLabel(this.actions);
    this.setCorruption(this.risk);
    if (this.actions >= 7) this.shake(45, 0.0015 * Math.min(4, this.actions - 5));
    emit("archive-sfx", { name: "action" });
  }

  updateMaze(dt) {
    const state = this.state;
    const previousHits = state.ball.collisions;
    stepBall(state.ball, dt);
    if (state.ball.collisions > previousHits) {
      this.timePenalty += PHYSICS.wallPenaltySeconds;
      this.remaining = Math.max(0, this.remaining - PHYSICS.wallPenaltySeconds);
      const penalty = this.add.text(clamp(state.ball.x, 85, WIDTH - 85), clamp(state.ball.y - 30, 155, HEIGHT - 60), "−1.00s", {
        fontFamily: "monospace", fontSize: "25px", color: "#ff947d", stroke: "#07141d", strokeThickness: 5,
      }).setOrigin(0.5).setDepth(10);
      this.tweens.add({ targets: penalty, y: penalty.y - 22, alpha: 0, delay: 250, duration: 500, onComplete: () => penalty.destroy() });
      emit("archive-wall-hit", { seconds: PHYSICS.wallPenaltySeconds });
      emit("archive-sfx", { name: "warning" });
      this.shake(90, 0.003);
      if (this.remaining <= 0) { this.finish(false); return; }
    }
    state.trail.unshift({ x: state.ball.x, y: state.ball.y });
    state.trail.length = Math.min(14, 4 + Math.floor(state.ball.multiplier * 3));
    this.trailGraphics.clear();
    state.trail.forEach((point, index) => {
      const alpha = 1 - index / state.trail.length;
      this.trailGraphics.fillStyle(0x56ddfb, alpha * 0.12 * state.ball.multiplier).fillCircle(point.x, point.y, BALL_RADIUS * alpha * 0.72);
    });
    this.player.setPosition(state.ball.x, state.ball.y);
    this.playerGlow.setPosition(state.ball.x, state.ball.y).setScale(0.95 + state.ball.multiplier * 0.1);

    const speed = Math.hypot(state.ball.vx, state.ball.vy);
    const inside = Math.hypot(state.ball.x - GOAL.x, state.ball.y - GOAL.y) <= GOAL.radius;
    if (inside && speed <= PHYSICS.goalMaxSpeed) state.goalHold += dt;
    else if (!inside) state.goalHold = 0;
    else state.goalHold = Math.max(0, state.goalHold - dt * 2);
    if (state.wasInside && !inside && state.goalHold < PHYSICS.goalHoldSeconds) state.overruns += 1;
    state.wasInside = inside;

    const progress = clamp(state.goalHold / PHYSICS.goalHoldSeconds, 0, 1);
    this.goalProgress.clear();
    if (progress > 0) {
      this.goalProgress.lineStyle(5, 0x93fca0, 1).beginPath().arc(GOAL.x, GOAL.y, GOAL.radius + 6, -Math.PI / 2, -Math.PI / 2 + Math.PI * 2 * progress).strokePath();
    }
    this.goalText.setText(inside && speed > PHYSICS.goalMaxSpeed ? "FAST" : `${Math.round(progress * 100)}%`)
      .setColor(inside && speed > PHYSICS.goalMaxSpeed ? "#ffb35d" : "#d9ffdd");
    if (progress >= 1) this.finish(true, `고속 통과 ${state.overruns}회`);
  }

  /* 02 — Gravity tower */
  buildGravity() {
    this.actions = 0;
    this.risk = 0;
    this.anomaly = "중력 1.0×";
    const platforms = [
      { x: 30, y: 500, w: 900, h: 20 },
      { x: 120, y: 415, w: 170, h: 16 },
      { x: 335, y: 330, w: 170, h: 16 },
      { x: 545, y: 245, w: 170, h: 16 },
      { x: 755, y: 160, w: 155, h: 16, goal: true },
    ];
    this.drawWalls(platforms, 0x3f4f65, 0x8399b4);
    this.add.text(850, 112, "GRAVITY BEACON", { fontFamily: "monospace", fontSize: "10px", color: "#93fca0" }).setOrigin(0.5);
    this.drawGoal(850, 128, 19, "TOP");
    this.gravityArrows = this.add.graphics().setDepth(2);
    this.state = {
      x: 75, y: 483, width: 26, height: 34, vx: 0, vy: 0,
      direction: null, onGround: true, support: platforms[0], gravity: 720, platforms,
    };
    this.player = this.add.rectangle(75, 483, 26, 34, 0xe9f6ff).setStrokeStyle(3, 0x7bc8ff).setDepth(5);
  }

  gravityPress(direction) {
    if (direction === "left" || direction === "right") this.state.direction = direction;
  }

  gravityJump() {
    const state = this.state;
    this.actions += 1;
    state.gravity = 720 + (this.actions - 1) * 112;
    if (state.onGround) {
      state.vy = -430;
      state.onGround = false;
      state.support = null;
    }
    this.risk = clamp((state.gravity - 720) / 780 * 100, 0, 100);
    this.anomaly = `중력 ${(state.gravity / 720).toFixed(1)}×`;
    this.setCorruption(this.risk * 0.7);
    emit("archive-sfx", { name: "action" });
  }

  updateGravity(dt) {
    const s = this.state;
    const previousBottom = s.y + s.height / 2;
    s.vx = s.direction === "left" ? -190 : s.direction === "right" ? 190 : 0;
    s.vy += s.gravity * dt;
    s.x = clamp(s.x + s.vx * dt, 48 + s.width / 2, 912 - s.width / 2);
    s.y += s.vy * dt;
    const newBottom = s.y + s.height / 2;

    if (s.onGround && s.support && (s.x + s.width / 2 < s.support.x || s.x - s.width / 2 > s.support.x + s.support.w)) {
      s.onGround = false;
      s.support = null;
    }
    if (s.vy >= 0) {
      for (const platform of s.platforms) {
        const horizontal = s.x + s.width / 2 > platform.x && s.x - s.width / 2 < platform.x + platform.w;
        if (horizontal && previousBottom <= platform.y + 3 && newBottom >= platform.y) {
          s.y = platform.y - s.height / 2;
          s.vy = 0;
          s.onGround = true;
          s.support = platform;
          this.shake(45, clamp(s.gravity / 500000, 0.0015, 0.004));
          if (platform.goal && s.x > 810) this.finish(true);
          break;
        }
      }
    }
    if (s.y > HEIGHT + 60) {
      s.x = 75;
      s.y = 483;
      s.vx = 0;
      s.vy = 0;
      s.onGround = true;
      s.support = s.platforms[0];
    }
    this.player.setPosition(s.x, s.y);
    if (s.support?.goal && s.x > 810) this.finish(true);
    this.gravityArrows.clear().lineStyle(2, 0xffb35d, 0.18 + this.risk / 170);
    for (let x = 72; x < 930; x += 74) {
      const length = 18 + this.risk * 0.28;
      this.gravityArrows.lineBetween(x, 52, x, 52 + length).lineBetween(x, 52 + length, x - 4, 62 + length).lineBetween(x, 52 + length, x + 4, 62 + length);
    }
  }

  /* 03 — Restitution loop */
  buildBounce() {
    this.actions = 0;
    this.risk = 0;
    this.anomaly = "탄성 1.0×";
    const walls = [
      ...boundaryWalls(28, 14),
      { x: 424, y: 150, w: 34, h: 338 },
      { x: 650, y: 230, w: 24, h: 282 },
    ];
    this.drawWalls(walls, 0x315169, 0x789bb7);
    this.drawGoal(830, 128, 28, "CORE");
    this.add.text(470, 126, "직선 경로 차단", { fontFamily: "monospace", fontSize: "10px", color: "#6f91a0" });
    this.state = {
      x: 118, y: 444, vx: 0, vy: 0, radius: 12, launched: false,
      walls, target: { x: 830, y: 128, radius: 28 }, collisionCooldown: 0, launchAge: 0,
    };
    this.player = this.add.circle(118, 444, 12, 0xf0f8ff).setStrokeStyle(3, 0xb7d4ff).setDepth(5);
    this.aimLine = this.add.graphics().setDepth(3);
  }

  launchBounceBall(x, y) {
    const s = this.state;
    const speed = Math.hypot(s.vx, s.vy);
    if (s.launched && speed > 34 && s.launchAge < 0.9) return;
    if (s.launched) {
      s.x = 118;
      s.y = 444;
      s.vx = 0;
      s.vy = 0;
    }
    const dx = x - s.x;
    const dy = y - s.y;
    const length = Math.max(1, Math.hypot(dx, dy));
    s.vx = dx / length * 470;
    s.vy = dy / length * 470;
    s.launched = true;
    s.launchAge = 0;
    emit("archive-sfx", { name: "action" });
  }

  updateBounce(dt) {
    const s = this.state;
    if (s.launched) s.launchAge += dt;
    if (!s.launched || Math.hypot(s.vx, s.vy) < 34) {
      const pointer = this.input.activePointer;
      this.aimLine.clear().lineStyle(2, 0x7bc8ff, 0.46).lineBetween(s.x, s.y, pointer.worldX, pointer.worldY);
    } else {
      this.aimLine.clear();
    }
    s.x += s.vx * dt;
    s.y += s.vy * dt;
    s.collisionCooldown = Math.max(0, s.collisionCooldown - dt);
    const restitution = clamp(0.88 + this.actions * 0.11, 0.88, 1.72);
    for (const wall of s.walls) {
      if (circleRectCollision(s, wall, restitution) && s.collisionCooldown <= 0) {
        this.actions += 1;
        s.collisionCooldown = 0.055;
        this.risk = clamp(this.actions / 7 * 100, 0, 100);
        this.anomaly = `탄성 ${Math.min(2.7, 1 + this.actions * 0.24).toFixed(1)}×`;
        this.setCorruption(this.risk);
        this.shake(55, clamp(0.0018 + this.actions * 0.00045, 0.0018, 0.006));
        emit("archive-sfx", { name: "warning" });
      }
    }
    const speed = Math.hypot(s.vx, s.vy);
    if (speed > 820) {
      s.vx = s.vx / speed * 820;
      s.vy = s.vy / speed * 820;
    }
    this.player.setPosition(s.x, s.y).setScale(1 + Math.min(0.65, this.actions * 0.07));
    if (Math.hypot(s.x - s.target.x, s.y - s.target.y) <= s.radius + s.target.radius) this.finish(true);
  }

  /* 04 — Recoil array */
  buildRecoil() {
    this.actions = 0;
    this.risk = 0;
    this.anomaly = "반동 정상";
    this.state = {
      turretX: 480,
      turretY: 468,
      bullets: [],
      hits: 0,
      time: 0,
      targets: [
        { x: 205, y: 150, baseX: 205, phase: 0, hit: false },
        { x: 480, y: 112, baseX: 480, phase: 2.1, hit: false },
        { x: 755, y: 165, baseX: 755, phase: 4.2, hit: false },
      ],
    };
    this.targetObjects = this.state.targets.map((target, index) => {
      const ring = this.add.circle(target.x, target.y, 27, 0xffb35d, 0.09).setStrokeStyle(3, 0xffb35d).setDepth(3);
      const text = this.add.text(target.x, target.y, String(index + 1), { fontFamily: "monospace", fontSize: "12px", color: "#ffd19d" }).setOrigin(0.5).setDepth(4);
      return { ring, text };
    });
    this.turret = this.add.rectangle(480, 468, 68, 28, 0x46788c).setStrokeStyle(2, 0x79cbe4).setDepth(4);
    this.barrel = this.add.rectangle(480, 440, 70, 9, 0xb8dfec).setOrigin(0.1, 0.5).setDepth(3);
    this.crosshair = this.add.circle(480, 220, 13, 0x000000, 0).setStrokeStyle(2, 0x93fca0, 0.8).setDepth(5);
    this.hitText = this.add.text(48, 60, "NODES 0 / 3", { fontFamily: "monospace", fontSize: "16px", color: "#93fca0" });
  }

  fireRecoilShot(x, y) {
    const s = this.state;
    this.actions += 1;
    const baseAngle = Math.atan2(y - s.turretY, x - s.turretX);
    const drift = this.actions === 1 ? 0 : (this.actions - 1) * 0.012 * (this.actions % 2 ? -1 : 1);
    const angle = baseAngle + drift;
    const speed = 720;
    const bullet = { x: s.turretX, y: s.turretY - 12, vx: Math.cos(angle) * speed, vy: Math.sin(angle) * speed };
    bullet.object = this.add.circle(bullet.x, bullet.y, 5, 0xe9fbff).setDepth(5);
    s.bullets.push(bullet);
    const recoil = 12 + this.actions * 6;
    s.turretX = clamp(s.turretX - Math.cos(angle) * recoil, 105, 855);
    this.risk = clamp(this.actions / 7 * 100, 0, 100);
    this.anomaly = `반동 ${Math.min(3.4, 1 + this.actions * 0.34).toFixed(1)}×`;
    this.setCorruption(this.risk * 0.85);
    this.shake(70, clamp(0.002 + this.actions * 0.0005, 0.002, 0.007));
    emit("archive-sfx", { name: "action" });
  }

  updateRecoil(dt) {
    const s = this.state;
    s.time += dt;
    const pointer = this.input.activePointer;
    this.crosshair.setPosition(pointer.worldX, pointer.worldY);
    const barrelAngle = Math.atan2(pointer.worldY - s.turretY, pointer.worldX - s.turretX);
    this.turret.setPosition(s.turretX, s.turretY);
    this.barrel.setPosition(s.turretX, s.turretY - 4).setRotation(barrelAngle);

    s.targets.forEach((target, index) => {
      if (target.hit) return;
      target.x = target.baseX + Math.sin(s.time * 1.35 + target.phase) * 34;
      this.targetObjects[index].ring.setPosition(target.x, target.y);
      this.targetObjects[index].text.setPosition(target.x, target.y);
    });

    for (let index = s.bullets.length - 1; index >= 0; index -= 1) {
      const bullet = s.bullets[index];
      const previous = { x: bullet.x, y: bullet.y };
      bullet.x += bullet.vx * dt;
      bullet.y += bullet.vy * dt;
      this.checkFragment({ x: bullet.x, y: bullet.y, radius: 5 }, previous);
      bullet.object.setPosition(bullet.x, bullet.y);
      let removed = false;
      for (let targetIndex = 0; targetIndex < s.targets.length; targetIndex += 1) {
        const target = s.targets[targetIndex];
        if (!target.hit && Math.hypot(bullet.x - target.x, bullet.y - target.y) <= 33) {
          target.hit = true;
          s.hits += 1;
          this.targetObjects[targetIndex].ring.setFillStyle(0x93fca0, 0.22).setStrokeStyle(3, 0x93fca0);
          this.targetObjects[targetIndex].text.setText("✓").setColor("#93fca0");
          bullet.object.destroy();
          s.bullets.splice(index, 1);
          removed = true;
          this.hitText.setText(`NODES ${s.hits} / 3`);
          emit("archive-sfx", { name: "hit" });
          if (s.hits === 3) this.finish(true, `${this.actions}발 사용`);
          break;
        }
      }
      if (!removed && (bullet.x < -20 || bullet.x > WIDTH + 20 || bullet.y < -20 || bullet.y > HEIGHT + 20)) {
        bullet.object.destroy();
        s.bullets.splice(index, 1);
      }
    }
  }

  /* 05 — Friction drop */
  buildFriction() {
    this.actions = 0;
    this.risk = 0;
    this.anomaly = "마찰 100%";
    const walls = [
      ...boundaryWalls(28, 14),
      { x: 278, y: 252, w: 30, h: 258 },
      { x: 520, y: 30, w: 30, h: 282 },
      { x: 728, y: 252, w: 30, h: 258 },
    ];
    this.drawWalls(walls, 0x3b5262, 0x7698aa);
    this.drawGoal(864, 72, 32, "DOCK");
    this.state = {
      x: 92, y: 452, vx: 0, vy: 0, radius: 15,
      direction: null, walls, goalHold: 0, wasInside: false, overruns: 0,
    };
    this.player = this.add.rectangle(92, 452, 30, 30, 0xffca75).setStrokeStyle(3, 0xffe1ad).setDepth(5);
    this.cargoTrail = this.add.graphics().setDepth(3);
    this.goalText = this.add.text(864, 72, "0%", { fontFamily: "monospace", fontSize: "10px", color: "#d9ffdd" }).setOrigin(0.5).setDepth(6);
  }

  frictionPress(direction) {
    this.state.direction = direction;
    this.actions += 1;
    const friction = Math.max(8, 100 - this.actions * 11);
    this.risk = clamp(100 - friction, 0, 100);
    this.anomaly = `마찰 ${friction}%`;
    this.setCorruption(this.risk * 0.75);
    emit("archive-sfx", { name: "action" });
  }

  updateFriction(dt) {
    const s = this.state;
    const vectors = { left: [-1, 0], right: [1, 0], up: [0, -1], down: [0, 1] };
    const [dx, dy] = vectors[s.direction] || [0, 0];
    const acceleration = 470;
    const drag = Math.max(55, 720 - this.actions * 82);
    if (dx) s.vx += dx * acceleration * dt; else s.vx = moveTowardZero(s.vx, drag * dt);
    if (dy) s.vy += dy * acceleration * dt; else s.vy = moveTowardZero(s.vy, drag * dt);
    const speed = Math.hypot(s.vx, s.vy);
    if (speed > 265) { s.vx = s.vx / speed * 265; s.vy = s.vy / speed * 265; }
    s.x += s.vx * dt;
    s.y += s.vy * dt;
    for (const wall of s.walls) circleRectCollision(s, wall, 0.02);
    this.player.setPosition(s.x, s.y).setRotation(Math.atan2(s.vy, s.vx) * 0.18);
    this.cargoTrail.clear().lineStyle(3, 0xffb35d, 0.14 + this.risk / 500).lineBetween(s.x - s.vx * 0.12, s.y - s.vy * 0.12, s.x, s.y);

    const currentSpeed = Math.hypot(s.vx, s.vy);
    const inside = Math.hypot(s.x - 864, s.y - 72) <= 32;
    if (inside && currentSpeed <= 78) s.goalHold += dt;
    else if (!inside) s.goalHold = 0;
    else s.goalHold = Math.max(0, s.goalHold - dt * 2);
    if (s.wasInside && !inside && s.goalHold < 0.4) s.overruns += 1;
    s.wasInside = inside;
    const progress = clamp(s.goalHold / 0.4, 0, 1);
    this.goalText.setText(inside && currentSpeed > 78 ? "FAST" : `${Math.round(progress * 100)}%`)
      .setColor(inside && currentSpeed > 78 ? "#ffb35d" : "#d9ffdd");
    if (progress >= 1) this.finish(true, `지나침 ${s.overruns}회`);
  }

  /* 06 — Light decay */
  buildDarkness() {
    this.actions = 0;
    this.risk = 0;
    this.anomaly = "광량 100%";
    const walls = [
      ...boundaryWalls(28, 14),
      { x: 28, y: 392, w: 330, h: 18 },
      { x: 358, y: 208, w: 18, h: 202 },
      { x: 190, y: 208, w: 488, h: 18 },
      { x: 678, y: 208, w: 18, h: 222 },
      { x: 500, y: 430, w: 196, h: 18 },
      { x: 790, y: 100, w: 18, h: 108 },
      { x: 808, y: 100, w: 122, h: 18 },
    ];
    this.drawWalls(walls, 0x263f4b, 0x65808d);
    this.drawGoal(865, 72, 24, "EXIT");
    this.state = { x: 86, y: 458, vx: 0, vy: 0, radius: 12, direction: null, walls, lightRadius: 230 };
    this.player = this.add.circle(86, 458, 12, 0xf6fbff).setStrokeStyle(3, 0xffe29d).setDepth(5);
    lightOverlay.classList.add("is-active");
    this.updateLightOverlay();
  }

  darknessPress(direction) {
    this.state.direction = direction;
    this.actions += 1;
    this.state.lightRadius = Math.max(58, 230 - this.actions * 19);
    this.risk = clamp((230 - this.state.lightRadius) / 172 * 100, 0, 100);
    this.anomaly = `광량 ${Math.round(this.state.lightRadius / 230 * 100)}%`;
    emit("archive-sfx", { name: this.actions >= 7 ? "warning" : "action" });
  }

  updateLightOverlay() {
    const s = this.state;
    lightOverlay.style.setProperty("--light-x", `${s.x / WIDTH * 100}%`);
    lightOverlay.style.setProperty("--light-y", `${s.y / HEIGHT * 100}%`);
    lightOverlay.style.setProperty("--light-radius", `${s.lightRadius / WIDTH * 100}%`);
  }

  updateDarkness(dt) {
    const s = this.state;
    const vectors = { left: [-1, 0], right: [1, 0], up: [0, -1], down: [0, 1] };
    const [dx, dy] = vectors[s.direction] || [0, 0];
    s.vx = dx * 185;
    s.vy = dy * 185;
    s.x += s.vx * dt;
    s.y += s.vy * dt;
    for (const wall of s.walls) circleRectCollision(s, wall, 0);
    this.player.setPosition(s.x, s.y);
    this.updateLightOverlay();
    if (Math.hypot(s.x - 865, s.y - 72) <= 34) this.finish(true);
  }

  /* 07 — Angular lock */
  buildRotation() {
    this.actions = 0;
    this.risk = 0;
    this.anomaly = "각속도 안정";
    const center = { x: 480, y: 272 };
    const targetAngle = 0.42;
    this.add.circle(center.x, center.y, 184, 0x0b2835, 0.32).setStrokeStyle(2, 0x315e70, 0.8);
    const ticks = this.add.graphics().lineStyle(2, 0x5e8797, 0.46);
    for (let i = 0; i < 24; i += 1) {
      const angle = i / 24 * Math.PI * 2;
      ticks.lineBetween(center.x + Math.cos(angle) * 171, center.y + Math.sin(angle) * 171, center.x + Math.cos(angle) * 183, center.y + Math.sin(angle) * 183);
    }
    this.add.line(center.x, center.y, 0, 0, Math.cos(targetAngle) * 340, Math.sin(targetAngle) * 340, 0x93fca0, 0.22).setLineWidth(12).setOrigin(0, 0.5);
    this.add.text(center.x + Math.cos(targetAngle) * 202, center.y + Math.sin(targetAngle) * 202, "LOCK ANGLE", { fontFamily: "monospace", fontSize: "10px", color: "#93fca0" }).setOrigin(0.5);
    this.rotationBar = this.add.rectangle(center.x, center.y, 330, 14, 0x9cdcef).setStrokeStyle(2, 0xe8fbff).setDepth(4);
    this.add.circle(center.x, center.y, 25, 0x173f50).setStrokeStyle(3, 0x65cce8).setDepth(5);
    this.rotationText = this.add.text(center.x, 486, "ALIGN 0%", { fontFamily: "monospace", fontSize: "15px", color: "#8daeba" }).setOrigin(0.5);
    this.state = { angle: -1.15, angularVelocity: 0, direction: null, targetAngle, hold: 0, center };
    this.rotationBar.setRotation(this.state.angle);
  }

  rotationPress(direction) {
    if (direction !== "left" && direction !== "right") return;
    this.state.direction = direction;
    this.actions += 1;
    this.risk = clamp(this.actions / 9 * 100, 0, 100);
    this.anomaly = `각속도 ${Math.min(3.8, 1 + this.actions * 0.31).toFixed(1)}×`;
    this.setCorruption(this.risk);
    emit("archive-sfx", { name: "action" });
  }

  updateRotation(dt) {
    const s = this.state;
    const direction = s.direction === "left" ? -1 : s.direction === "right" ? 1 : 0;
    const torque = 2.45 * (1 + this.actions * 0.16);
    const damping = Math.max(0.22, 1.32 - this.actions * 0.1);
    if (direction) s.angularVelocity += direction * torque * dt;
    else s.angularVelocity = moveTowardZero(s.angularVelocity, damping * dt);
    const maxVelocity = 1.55 + this.actions * 0.27;
    s.angularVelocity = clamp(s.angularVelocity, -maxVelocity, maxVelocity);
    s.angle += s.angularVelocity * dt;
    if (s.angle > Math.PI) s.angle -= Math.PI * 2;
    if (s.angle < -Math.PI) s.angle += Math.PI * 2;
    this.rotationBar.setRotation(s.angle);

    const angleError = Math.abs(Math.atan2(Math.sin(s.angle - s.targetAngle), Math.cos(s.angle - s.targetAngle)));
    const valid = angleError <= 0.09 && Math.abs(s.angularVelocity) <= 0.22;
    if (valid) s.hold += dt; else s.hold = Math.max(0, s.hold - dt * 1.5);
    const progress = clamp(s.hold / 0.65, 0, 1);
    this.rotationText.setText(valid ? `LOCK ${Math.round(progress * 100)}%` : `ERROR ${(angleError * 180 / Math.PI).toFixed(1)}°`)
      .setColor(valid ? "#93fca0" : "#8daeba");
    if (progress >= 1) this.finish(true, `각도 오차 ${(angleError * 180 / Math.PI).toFixed(1)}°`);
  }
}

window.archivePhaserGame = new Phaser.Game({
  type: Phaser.AUTO,
  width: WIDTH,
  height: HEIGHT,
  parent: "game-container",
  backgroundColor: "#07141d",
  render: { antialias: true, pixelArt: false },
  scale: { mode: Phaser.Scale.FIT, autoCenter: Phaser.Scale.CENTER_BOTH },
  scene: ArchiveGame,
});

})();
