$ErrorActionPreference = "Stop"

$projectRoot = Split-Path -Parent $PSScriptRoot
$archiveRoot = Join-Path $projectRoot "js\archive"
$outputPath = Join-Path $archiveRoot "game-classic.js"
$sourceNames = @(
  "data.mjs",
  "audio.mjs",
  "level-data.mjs",
  "physics-core.mjs",
  "gravity-core.mjs",
  "bounce-core.mjs",
  "stack-core.mjs",
  "progress.mjs",
  "fragments.mjs",
  "game.mjs"
)

$parts = foreach ($sourceName in $sourceNames) {
  $sourcePath = Join-Path $archiveRoot $sourceName
  $source = [IO.File]::ReadAllText($sourcePath)
  $source = [Text.RegularExpressions.Regex]::Replace(
    $source,
    "(?m)^import\s+.*?;\r?\n",
    ""
  )
  $source = [Text.RegularExpressions.Regex]::Replace(
    $source,
    "(?m)^export\s+",
    ""
  )

  # physics-core and game originally have separate module scopes. Once bundled,
  # their private helpers share one scope, so keep the physics helper distinct.
  if ($sourceName -eq "physics-core.mjs") {
    $source = $source.Replace("moveTowardZero", "physicsMoveTowardZero")
  }

  "`n/* Source: $sourceName */`n$source"
}

$banner = @"
/*
 * Generated by scripts/build-archive-classic.ps1.
 * This classic-script bundle mirrors js/archive/*.mjs so index.html also works
 * when opened directly through file://, where browsers block ES module imports.
 */
(function () {
"@
$footer = "`n})();`n"
$content = $banner + ($parts -join "`n") + $footer
[IO.File]::WriteAllText($outputPath, $content, [Text.UTF8Encoding]::new($false))
Write-Output "Built $outputPath"
