$ErrorActionPreference = "Stop"

$projectRoot = Split-Path -Parent $PSScriptRoot
$archiveRoot = Join-Path $projectRoot "js\archive"
$outputPath = Join-Path $archiveRoot "game-classic.js"
$sourceNames = @(
  "data.mjs",
  "audio.mjs",
  "progress.mjs",
  "records.mjs",
  "plays.mjs",
  "run-state.mjs",
  "stages/minigame-kit.js",
  "stages/e1_gravityDash.js",
  "stages/e2_bounceBall.js",
  "stages/e3_humanStack.js",
  "stages/e4_accelerationDash.js",
  "stages/e5_slingshot.js",
  "stages/e6_gravityFlight.js",
  "stages/e7_roulette.js",
  "stages/e8_webSwing.js",
  "stages/e10_numberDecode.js",
  "stages/index.mjs",
  "game.mjs"
)

$parts = foreach ($sourceName in $sourceNames) {
  $sourcePath = Join-Path $archiveRoot $sourceName
  $source = [IO.File]::ReadAllText($sourcePath)
  $source = [Text.RegularExpressions.Regex]::Replace(
    $source,
    "(?m)^import\s+.*?;\r?\n",
    ""
  )
  $source = [Text.RegularExpressions.Regex]::Replace(
    $source,
    "(?m)^export\s+",
    ""
  )

  "`n/* Source: $sourceName */`n$source"
}

$banner = @"
/*
 * Generated by scripts/build-archive-classic.ps1.
 * This classic-script bundle mirrors js/archive/*.mjs and stages/eN_*.js and
 * stages/minigame-kit.js so index.html also works
 * when opened directly through file://, where browsers block ES module imports.
 */
(function () {
"@
$footer = "`n})();`n"
$content = $banner + ($parts -join "`n") + $footer
[IO.File]::WriteAllText($outputPath, $content, [Text.UTF8Encoding]::new($false))
Write-Output "Built $outputPath"
